version: "3.9"
services:
  update_from_remote_schema:
    build: .
    command: bash -c "chown -R root /lune-ts && cd /lune-ts && make build-from-schema"
    volumes:
      - .:/lune-ts
  build_from_source:
    build: .
    command: bash -c "chown -R root /lune-ts && cd /lune-ts && make build-from-source"
    volumes:
      - .:/lune-ts
