version: "3.9"
services:
  update_from_remote_schema:
    build: .
    command: bash -c "ls -lah / && ls -lah ~ && whoami && env && cd /lune-ts && make build-from-schema"
    volumes:
      - .:/lune-ts
  build_from_source:
    build: .
    # See the update_from_remote_schema chown comment above for some context.
    command: bash -c "cd /lune-ts && make build-from-source"
    volumes:
      - .:/lune-ts
  bump_version_patch:
    build: .
    command: bash -c "cd /lune-ts && make patch-version"
    volumes:
      - .:/lune-ts
  bump_version_minor:
    build: .
    command: bash -c "cd /lune-ts && make minor-version"
    volumes:
      - .:/lune-ts
  bump_version_major:
    build: .
    command: bash -c "cd /lune-ts && make major-version"
    volumes:
      - .:/lune-ts
