// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { CreateShipmentRequest } from '../models/CreateShipmentRequest.js'
import type { PaginatedShipments } from '../models/PaginatedShipments.js'
import type { Shipment } from '../models/Shipment.js'
import type { ShipmentBatch } from '../models/ShipmentBatch.js'
import type { ShipmentModeOfTransport } from '../models/ShipmentModeOfTransport.js'

import { ClientConfig } from '../core/ClientConfig.js'
import { request as __request } from '../core/request.js'
import { SuccessResponse } from '../core/SuccessResponse.js'
import { ApiError } from '../core/ApiError.js'
import { AxiosInstance } from 'axios'
import { Result } from 'ts-results-es'

export abstract class ShipmentsService {
    protected abstract client: AxiosInstance
    protected abstract config: ClientConfig

    /**
     * List shipments
     * Returns the account's paginated shipments in reverse order (most recent first).
     * @param data Request data
     * @param options Additional operation options
     * @returns PaginatedShipments OK
     */
    public listShipments(
        data?: {
            /**
             * Maximum number of resources to return, between 1 and 100.
             *
             */
            limit?: string
            /**
             * A cursor for use in pagination.
             *
             * The cursor that points to the starting item of the next page of results. If not provided, the first page of results is returned.
             *
             */
            after?: string
            /**
             * Free-text search term used to match shipment IDs in the returned results.
             *
             */
            search?: string
            /**
             * Include only shipments with a shipment date on or after this date.
             *
             */
            shipmentDateFrom?: string
            /**
             * Include only shipments with a shipment date on or before this date.
             *
             */
            shipmentDateTo?: string
            /**
             * Filter shipments by the main carriage mode of transport.
             *
             */
            mainCarriageMot?: Array<ShipmentModeOfTransport>
            /**
             * Filter shipments by the pre-carriage mode of transport.
             *
             */
            preCarriageMot?: Array<ShipmentModeOfTransport>
            /**
             * Filter shipments by the post-carriage mode of transport.
             *
             */
            postCarriageMot?: Array<ShipmentModeOfTransport>
            /**
             * Filter shipments by supplier account IDs.
             *
             */
            supplierId?: Array<string>
            /**
             * Filter shipments by shipper account IDs.
             *
             */
            shipperId?: Array<string>
            /**
             * Filter shipments by the IDs of the shipment batches they were created from.
             *
             */
            shipmentBatchId?: Array<string>
            /**
             * Filter shipments by whether they contain legs with flagged emission intensity.
             *
             */
            flagged?: boolean
            /**
             * Filter shipments by emissions availability.
             *
             */
            emissions?: 'all' | 'with_co2e' | 'without_co2e'
        },
        options?: {
            /**
             * Account Id to be used to perform the API call
             */
            accountId?: string
        },
    ): Promise<Result<SuccessResponse<PaginatedShipments>, ApiError>> {
        return __request(this.client, this.config, options || {}, {
            method: 'GET',
            url: '/shipments',
            headers: {
                Accept: 'application/json',
            },
            query: {
                limit: data?.limit,
                after: data?.after,
                search: data?.search,
                shipment_date_from: data?.shipmentDateFrom,
                shipment_date_to: data?.shipmentDateTo,
                main_carriage_mot: data?.mainCarriageMot,
                pre_carriage_mot: data?.preCarriageMot,
                post_carriage_mot: data?.postCarriageMot,
                supplier_id: data?.supplierId,
                shipper_id: data?.shipperId,
                shipment_batch_id: data?.shipmentBatchId,
                flagged: data?.flagged,
                emissions: data?.emissions,
            },
            errors: {
                400: `The request is invalid. Parameters may be missing or are invalid`,
                401: `The API Key is missing or is invalid`,
                429: `Too many requests have been made in a short period of time`,
            },
        })
    }

    /**
     * Upload a batch of shipments
     * Submit a batch of shipments for emission reporting.
     *
     * Only rudimentary checks (e.g. payload structure and size) are performed
     * at upload time. The request either succeeds as a whole or it does not;
     * there are no per-row errors on upload. Detailed per-row validation
     * happens asynchronously when the batch is processed.
     *
     * The counterparty on each resulting shipment is resolved from
     * one of two sources:
     *
     * 1. If `contact_id` is supplied on the request, the identified contact
     * is the counterparty for every resulting shipment. Per-row
     * `target_internal_id` and `target_internal_name` are ignored for
     * counterparty resolution in this case.
     * 2. Otherwise, each row's counterparty is resolved from its per-row
     * `target_internal_id`, scoped to the authenticated account.
     * `target_internal_name` is used when the system has to create a
     * previously-unseen counterparty mapping.
     *
     * Supplying both `contact_id` on the request and `target_internal_id`
     * on a row is not an error; `contact_id` wins. Rows without a usable
     * counterparty when `contact_id` is absent will fail during asynchronous
     * processing.
     *
     * The `shipper_id` and `supplier_id` on each resulting shipment
     * are derived from the authenticated account and the resolved
     * counterparty: a shipper account is assigned as `shipper_id`,
     * otherwise it is assigned as `supplier_id`, and the counterparty
     * takes the opposite role.
     *
     * Returns a batch identifier that can be used to refer to the batch later.
     *
     * @param data Request data
     * @param options Additional operation options
     * @returns any OK
     */
    public createShipmentBatch(
        data: {
            shipments: Array<CreateShipmentRequest>
            /**
             * Lune contact identifier for the counterparty in this batch.
             * When supplied, every row in the batch uses the identified contact
             * as the counterparty and per-row `target_internal_id` /
             * `target_internal_name` are ignored for counterparty resolution.
             * When omitted, each row's counterparty is resolved from its
             * per-row `target_internal_id` instead.
             *
             */
            contactId?: string
            /**
             * Idempotency key for this batch upload, unique per authenticated
             * account. Returns HTTP 409 Conflict with error code
             * `shipment_batch_idempotency_already_exists` if a batch with the
             * same idempotency key has already been submitted by this account.
             *
             */
            idempotencyKey?: string
            /**
             * Whether to schedule emission calculations immediately after this
             * batch has been processed. Defaults to false.
             *
             */
            calculateEmissions?: boolean
        },
        options?: {
            /**
             * Account Id to be used to perform the API call
             */
            accountId?: string
        },
    ): Promise<
        Result<
            SuccessResponse<{
                /**
                 * Batch identifier.
                 */
                id: string
            }>,
            ApiError
        >
    > {
        return __request(this.client, this.config, options || {}, {
            method: 'POST',
            url: '/shipments/batches',
            headers: {
                Accept: 'application/json',
            },
            body: {
                shipments: data?.shipments,
                contact_id: data?.contactId,
                idempotency_key: data?.idempotencyKey,
                calculate_emissions: data?.calculateEmissions,
            },
            mediaType: 'application/json',
            errors: {
                400: `The request is invalid. Parameters may be missing or are invalid`,
                401: `The API Key is missing or is invalid`,
                409: `The request could not be completed due to a conflict with the current state of the target resource or resources`,
                413: `The request is larger than 100kB.`,
                415: `The payload format is in an unsupported format.`,
                429: `Too many requests have been made in a short period of time`,
                503: `The service is temporarily unavailable. You may retry.`,
            },
        })
    }

    /**
     * Get a shipment batch
     * Fetch the current processing state of a shipment batch. Row
     * results and counts are included when row processing has run to
     * completion.
     *
     * @param id Shipment batch identifier.
     * @param options Additional operation options
     * @returns ShipmentBatch OK
     */
    public getShipmentBatch(
        id: string,
        options?: {
            /**
             * Account Id to be used to perform the API call
             */
            accountId?: string
        },
    ): Promise<Result<SuccessResponse<ShipmentBatch>, ApiError>> {
        return __request(this.client, this.config, options || {}, {
            method: 'GET',
            url: '/shipments/batches/{id}',
            path: {
                id: id,
            },
            headers: {
                Accept: 'application/json',
            },
            errors: {
                401: `The API Key is missing or is invalid`,
                404: `The specified resource was not found`,
                429: `Too many requests have been made in a short period of time`,
            },
        })
    }

    /**
     * Get a shipment
     * Retrieve a shipment by its identifier, including calculated emissions
     * when available.
     *
     * @param id The shipment's unique identifier.
     * @param options Additional operation options
     * @returns Shipment OK
     */
    public getShipment(
        id: string,
        options?: {
            /**
             * Account Id to be used to perform the API call
             */
            accountId?: string
        },
    ): Promise<Result<SuccessResponse<Shipment>, ApiError>> {
        return __request(this.client, this.config, options || {}, {
            method: 'GET',
            url: '/shipments/{id}',
            path: {
                id: id,
            },
            headers: {
                Accept: 'application/json',
            },
            errors: {
                401: `The API Key is missing or is invalid`,
                404: `The specified resource was not found`,
                429: `Too many requests have been made in a short period of time`,
            },
        })
    }
}
