// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * A unique identifier provided by the client.
 *
 * `idempotency_key` is unique per account type.
 *
 * The property ensures Accounts created with an existing `idempotency_key` are not created.
 *
 */
export type AccountIdempotencyKey = string
