// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * The account's scope.
 *
 * Determines if the resource is a regular account or a client account.
 *
 */
export enum AccountScope {
    ACCOUNT = 'account',
    CLIENT_ACCOUNT = 'client_account',
}
