// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * The account's currency.
 *
 * ISO 4217 3 character currency code.
 *
 * Note: Lune does not support all currency codes.
 *
 */
export enum AccountCurrencyCode {
    GBP = 'GBP',
    EUR = 'EUR',
    USD = 'USD',
    SEK = 'SEK',
    CHF = 'CHF',
    PLN = 'PLN',
    DKK = 'DKK',
    NOK = 'NOK',
    BGN = 'BGN',
    INR = 'INR',
    SGD = 'SGD',
    AED = 'AED',
    AUD = 'AUD',
    HUF = 'HUF',
    ISK = 'ISK',
    CZK = 'CZK',
    CAD = 'CAD',
}
