// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * Controls the visibility of external pages such as sustainability and analytics pages.
 *
 * `public` pages are visible to everyone.
 * `private` pages are only visible through a verified JWT.
 * `hidden` pages not visible.
 *
 * Defaults to `hidden`.
 *
 */
export enum AccountExternalPagesVisibility {
    PUBLIC = 'public',
    HIDDEN = 'hidden',
    PRIVATE = 'private',
}
