// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * A unique identifier provided by the client.
 *
 * `idempotency_key` is unique per account type.
 *
 * If an account with the same `idempotency_key` already exists, the API returns
 * HTTP 409 Conflict with error code `account_idempotency_already_exists`.
 *
 */
export type AccountIdempotencyKey = string
