// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { AccountType } from './AccountType.js'
import type { ShippingCarbonIntensityTimeseries } from './ShippingCarbonIntensityTimeseries.js'
import type { ShippingEmissionTimeseries } from './ShippingEmissionTimeseries.js'

export type AnalyticsShippingEstimates = {
    emissionTimeseries: ShippingEmissionTimeseries
    carbonIntensityTimeseries: ShippingCarbonIntensityTimeseries
    /**
     * Information about the account the analytics are associated with.
     */
    account: {
        /**
         * The account's name.
         */
        name: string
        /**
         * The account's type.
         */
        type: AccountType
        /**
         * The account's logo URL.
         */
        logo: string | null
    }
}
