// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * Analytics endpoints return data which help you analyse and understand your activity.
 *
 * For instance, you may request emission estimates over time or carbon credit purchases by location.
 *
 */
export type Analytics = {}
