// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { SupportedUNSdg } from './SupportedUNSdg.js'

export type AnalyticsMetrics = {
    /**
     * The number of supported UN Sustainable Development Goals (SDGs).
     */
    numberOfUnSdgs: number
    /**
     * The number of supported carbon offset projects.
     */
    numberOfProjects: number
    unSdg: SupportedUNSdg
}
