// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { QuantityAndValueTimeseries } from './QuantityAndValueTimeseries.js'

export type AnalyticsByBundle = {
    /**
     * The bundle's unique identifier
     */
    bundleId: string
    /**
     * The bundle's name
     */
    bundleName: string
    timeseries: QuantityAndValueTimeseries
}
