// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { MultiLegShippingEmissionEstimate } from './MultiLegShippingEmissionEstimate.js'
import type { SingleShippingEmissionEstimate } from './SingleShippingEmissionEstimate.js'

export type AnyShippingEmissionEstimate =
    | SingleShippingEmissionEstimate
    | MultiLegShippingEmissionEstimate
