// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type Area = {
    amount: string
    unit: Area.unit
}

export namespace Area {
    export enum unit {
        SQUARE_METERS = 'square_meters',
        SQUARE_FEET = 'square_feet',
    }
}
