// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { Distance } from './Distance.js'
import type { EmissionFactorWithGasEmissions } from './EmissionFactorWithGasEmissions.js'
import type { NullEnum } from './NullEnum.js'

export type BaseTransactionPassengerEstimate = {
    distance: Distance
    /**
     * This property is `null` for any estimate created before 01/12/2024
     */
    emissionFactor: EmissionFactorWithGasEmissions | NullEnum
    /**
     * The line items that has been identified.
     */
    item: string
    /**
     * Number of passengers the calculation should be applied to.
     */
    passengers: number
}
