// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * Maps a bundle's unique identifier to an allocation ratio
 */
export type BundlePercentage = {
    /**
     * The bundle's unique identifier
     */
    bundleId: string
    percentage: number | string
}
