// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { CalculatedRouteLeg } from './CalculatedRouteLeg.js'
import type { CalculatedRouteLocation } from './CalculatedRouteLocation.js'

/**
 * A list of locations and distances betwen them.
 *
 * At least one leg will always exist.
 *
 * The last leg contains the final location (destination) of the route.
 *
 */
export type CalculatedRoute = {
    source: CalculatedRouteLocation
    legs: Array<CalculatedRouteLeg>
    /**
     * Attribution for the route provider, if applicable.
     */
    attribution: string | null
}
