// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type CalculationBatchRowSuccess = {
    /**
     * Zero-based index of the requested shipment.
     */
    rowIndex: number
    status: CalculationBatchRowSuccess.status
    /**
     * Lune-provided shipment identifier.
     */
    id: string
    /**
     * Lune estimate identifier, or null when no Lune estimate was created.
     */
    estimateId: string | null
}

export namespace CalculationBatchRowSuccess {
    export enum status {
        SUCCESS = 'success',
    }
}
