// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type CalculationBatchRowFailure = {
    /**
     * Zero-based index of the requested shipment.
     */
    rowIndex: number
    status: CalculationBatchRowFailure.status
    /**
     * Lune-provided shipment identifier.
     */
    id: string
    /**
     * Public row-level calculation error.
     */
    error: string
}

export namespace CalculationBatchRowFailure {
    export enum status {
        FAILED = 'failed',
    }
}
