// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { PendingCalculationBatch } from './PendingCalculationBatch.js'
import type { ProcessedCalculationBatchWithError } from './ProcessedCalculationBatchWithError.js'
import type { ProcessedCalculationBatchWithResults } from './ProcessedCalculationBatchWithResults.js'
import type { ProcessingCalculationBatch } from './ProcessingCalculationBatch.js'

export type CalculationBatch =
    | PendingCalculationBatch
    | ProcessingCalculationBatch
    | ProcessedCalculationBatchWithResults
    | ProcessedCalculationBatchWithError
