// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * The bundle's carbon storage permanence.
 */
export enum CarbonPermanence {
    LONG_TERM = 'long_term',
    SHORT_TERM = 'short_term',
    NO_STORAGE = 'no_storage',
}
