// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * Specify the mass of cargo in the container. If omitted, `average` is used by default.
 *
 * Each type applies a different conversion to mass for emissions estimation. See [TEU conversion table](https://docs.lune.co/general-concepts/logistics-methodology#13-cargo-weight) for details.
 *
 */
export enum CargoType {
    LIGHTWEIGHT = 'lightweight',
    AVERAGE = 'average',
    HEAVYWEIGHT = 'heavyweight',
    CONTAINER_ONLY = 'container_only',
}
