// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * Indicates the leg's role in the overall shipment journey.
 *
 * * `pre` — first-mile pickup
 * * `main` — primary long-haul
 * * `on` — last-mile delivery
 *
 */
export enum CarriageType {
    PRE = 'pre',
    MAIN = 'main',
    ON = 'on',
}
