// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { ClientAccount } from './ClientAccount.js'

export type ClientAccountWithAnalyticSummary = ClientAccount & {
    /**
     * The time of the last estimate created by the account. If the account | has never created an estimate, this is null.
     */
    lastActiveDate: string | null
    /**
     * All-time number of estimates created by given account.
     */
    numberOfEstimates: number
    /**
     * All-time tCO2e calculated in estimates created by given account.
     */
    totalEmissions: string
}
