// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * Client-provided emissions data for a shipment leg.
 * All emission values are in kilograms.
 *
 */
export type ClientProvidedLegEmissions = {
    /**
     * Total emissions (kg CO2e).
     */
    totalEmissions?: string
    /**
     * Well-to-tank emissions (kg CO2e).
     */
    wtt?: string
    /**
     * Tank-to-wheel emissions (kg CO2e).
     */
    ttw?: string
    /**
     * Emission intensity.
     */
    intensity?: string | null
    /**
     * Total particulate matter emissions (kg).
     */
    particlesTotal?: string | null
    /**
     * Well-to-tank particulate matter emissions (kg).
     */
    particlesWtt?: string | null
    /**
     * Tank-to-wheel particulate matter emissions (kg).
     */
    particlesTtw?: string | null
    /**
     * Total carbon dioxide emissions (kg).
     */
    carbonDioxideTotal?: string | null
    /**
     * Well-to-tank carbon dioxide emissions (kg).
     */
    carbonDioxideWtt?: string | null
    /**
     * Tank-to-wheel carbon dioxide emissions (kg).
     */
    carbonDioxideTtw?: string | null
    /**
     * Total nitrogen oxides emissions (kg).
     */
    nitrogenOxidesTotal?: string | null
    /**
     * Well-to-tank nitrogen oxides emissions (kg).
     */
    nitrogenOxidesWtt?: string | null
    /**
     * Tank-to-wheel nitrogen oxides emissions (kg).
     */
    nitrogenOxidesTtw?: string | null
    /**
     * Total sulfur dioxides emissions (kg).
     */
    sulfurDioxidesTotal?: string | null
    /**
     * Well-to-tank sulfur dioxides emissions (kg).
     */
    sulfurDioxidesWtt?: string | null
    /**
     * Tank-to-wheel sulfur dioxides emissions (kg).
     */
    sulfurDioxidesTtw?: string | null
    /**
     * Total non-methane hydrocarbons emissions (kg).
     */
    nonMethaneHydroCarbonsTotal?: string | null
    /**
     * Well-to-tank non-methane hydrocarbons emissions (kg).
     */
    nonMethaneHydroCarbonsWtt?: string | null
    /**
     * Tank-to-wheel non-methane hydrocarbons emissions (kg).
     */
    nonMethaneHydroCarbonsTtw?: string | null
    /**
     * Primary energy consumption (MJ).
     */
    primaryEnergyMj?: string | null
    /**
     * Fuel consumption (litres).
     */
    fuelConsumptionL?: string | null
    /**
     * Distance (km).
     */
    distanceKm?: string | null
    /**
     * Transport activity (tonne-kilometres).
     */
    transportActivity?: string | null
    /**
     * Source of the emissions data.
     */
    emissionsSource?: ClientProvidedLegEmissions.emissions_source
    /**
     * Description of the emission factor used.
     */
    emissionFactorDescription?: string
    /**
     * Region of the emission factor.
     */
    emissionFactorRegion?: string
    /**
     * Source of the emission factor.
     */
    emissionFactorSource?: string
    /**
     * Intensity value of the emission factor.
     */
    emissionFactorIntensity?: string | null
    /**
     * Numerator unit of the emission factor.
     */
    emissionFactorNumerator?: string
    /**
     * Denominator unit of the emission factor.
     */
    emissionFactorDenominator?: string
    /**
     * Year of the emission factor.
     */
    emissionFactorYear?: number
}

export namespace ClientProvidedLegEmissions {
    /**
     * Source of the emissions data.
     */
    export enum emissions_source {
        ECOTRANSIT = 'ecotransit',
        LUNE = 'lune',
        MANUAL = 'manual',
    }
}
