// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * The identifier of a cloud provider.
 */
export enum CloudProvider {
    AWS = 'aws',
    GCP = 'gcp',
    AZURE = 'azure',
    OVH = 'ovh',
    OTHER = 'other',
}
