// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { CloudProvider } from './CloudProvider.js'
import type { MonetaryAmount } from './MonetaryAmount.js'

/**
 * Company's use of cloud services
 */
export type CompanyCloudUse = {
    cost: MonetaryAmount
    provider: CloudProvider
}
