// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { Incoterm } from './Incoterm.js'
import type { Metadata } from './Metadata.js'
import type { MonetaryAmount } from './MonetaryAmount.js'
import type { ShipmentContractType } from './ShipmentContractType.js'
import type { ShipmentLeg } from './ShipmentLeg.js'
import type { ShipmentServiceLevel } from './ShipmentServiceLevel.js'
import type { ShipmentTour } from './ShipmentTour.js'

export type CreateShipmentRequest = {
    /**
     * Client-side shipment reference identifier.
     */
    shipmentId?: string
    /**
     * Idempotency key for the request. A 409 Conflict is returned if a
     * shipment with the same idempotency key already exists.
     *
     */
    idempotencyKey?: string
    metadata?: Metadata
    /**
     * Tags for categorising or filtering shipments.
     */
    tags?: Array<string>
    serviceLevel?: ShipmentServiceLevel
    incoterm?: Incoterm
    contractType?: ShipmentContractType
    /**
     * Whether the shipment contains hazardous cargo.
     */
    hazardousCargo?: boolean
    /**
     * Booking reference number.
     */
    bookingReference?: string
    /**
     * House waybill number.
     */
    houseWaybill?: string
    /**
     * Purchase order reference identifier.
     */
    referenceIdPo?: string
    /**
     * Client-side identifier for the consignee.
     */
    consigneeId?: string
    /**
     * Name of the consignee.
     */
    consigneeName?: string
    /**
     * Client-side identifier for the consignor.
     */
    consignorId?: string
    /**
     * Name of the consignor.
     */
    consignorName?: string
    /**
     * Name of the freight paying party.
     */
    freightPayingParty?: string
    /**
     * Legal entity responsible for the shipment.
     */
    legalEntity?: string
    freightCost?: MonetaryAmount
    /**
     * Emission scope for the shipper contract.
     */
    shipperContractEmissionScope?: string
    tour?: ShipmentTour
    legs: Array<ShipmentLeg>
}
