// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { CreateShipmentRoadEmissionStandard } from './CreateShipmentRoadEmissionStandard.js'
import type { CreateShipmentRoadFuel } from './CreateShipmentRoadFuel.js'
import type { FuelConsumption } from './FuelConsumption.js'
import type { RoadGradient } from './RoadGradient.js'
import type { RoadSituation } from './RoadSituation.js'
import type { RoadVehicleType } from './RoadVehicleType.js'

/**
 * Road transport method accepted when creating a shipment.
 *
 */
export type CreateShipmentRoadMethod = {
    /**
     * Vehicle type used for shipping.
     *
     */
    vehicleType: RoadVehicleType | 'truck'
    fuel: CreateShipmentRoadFuel
    /**
     * Describes the road's topology.
     *
     */
    gradient?: RoadGradient
    /**
     * Situation describes the driving environment and road condition.
     *
     */
    situation?: RoadSituation
    /**
     * The vehicle's emission standard for pollution.
     *
     */
    emissionStandard?: CreateShipmentRoadEmissionStandard
    /**
     * The shipment is refrigerated or "dry" (not refrigerated).
     *
     */
    refrigerated?: boolean
    /**
     * License plate number of the truck.
     */
    truckLicensePlate?: string
    /**
     * License plate number of the trailer.
     */
    trailerLicensePlate?: string
    /**
     * Vehicle Identification Number.
     */
    vin?: string
    /**
     * Primary fuel consumption for this leg.
     */
    fuelConsumption?: FuelConsumption
    /**
     * Share of biofuel in the fuel mix (0 to 1).
     */
    biofuelShare?: string | null
}
