// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { BundleSelectionRequest } from './BundleSelectionRequest.js'
import type { Mass } from './Mass.js'
import type { Metadata } from './Metadata.js'
import type { QuantityTrunc } from './QuantityTrunc.js'

/**
 * Order by Quantity details
 */
export type CreateOrderByQuantityWithBundlePercentage = {
    /**
     * Mass of CO2 offsets to purchase
     */
    mass: Mass
    /**
     * Account-unique identifier provided by the client.
     *
     * `idempotency_key` has two purposes:
     * 1. Clients can use `idempotency_key` to prevent duplicate orders.
     * 2. Clients can use `idempotency_key` to reconcile orders with other entities on their system.
     *
     * If an order with the same `idempotency_key` already exists, the API returns
     * HTTP 409 Conflict with error code `order_idempotency_already_exists`. To
     * retrieve the existing order, use the
     * `GET /v1/orders/by-idempotency-key/{idempotency_key}` endpoint.
     *
     */
    idempotencyKey?: string
    /**
     * Bundle selection to be used for the order.
     * For the order, this property overrides the account's bundle selection.
     *
     */
    bundleSelection?: BundleSelectionRequest
    metadata?: Metadata
    quantityTrunc?: QuantityTrunc
}
