// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { BundleMass } from './BundleMass.js'
import type { Metadata } from './Metadata.js'
import type { QuantityTrunc } from './QuantityTrunc.js'

/**
 * Order by Quantity details
 */
export type CreateOrderByQuantityWithBundleMass = {
    /**
     * An array of `{ bundle_id, mass }` objects.
     *
     * Populate the array to purchase carbon credits, belonging to multiple bundles, by quantity, eg 20 tCO₂.
     *
     */
    bundleMasses: Array<BundleMass>
    /**
     * Account-unique identifier provided by the client.
     *
     * `idempotency_key` has two purposes:
     * 1. Clients can use `idempotency_key` to prevent duplicate orders.
     * 2. Clients can use `idempotency_key` to reconcile orders with other entities on their system.
     *
     * If an order with the same `idempotency_key` already exists, the API returns
     * HTTP 409 Conflict with error code `order_idempotency_already_exists`. To
     * retrieve the existing order, use the
     * `GET /v1/orders/by-idempotency-key/{idempotency_key}` endpoint.
     *
     */
    idempotencyKey?: string
    metadata?: Metadata
    quantityTrunc?: QuantityTrunc
}
