// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { AnalyticsByBundle } from './AnalyticsByBundle.js'

/**
 * An array of analytics by bundle objects.
 */
export type CumulativeBundleAnalytics = Array<AnalyticsByBundle>
