// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type DataQualityScore = {
    /**
     * The quality score represented as a letter grade. Grades range from "A_plus" (excellent) to "D" (unsatisfactory).
     *
     */
    score: DataQualityScore.score
}

export namespace DataQualityScore {
    /**
     * The quality score represented as a letter grade. Grades range from "A_plus" (excellent) to "D" (unsatisfactory).
     *
     */
    export enum score {
        A_PLUS = 'A_plus',
        A = 'A',
        A_MINUS = 'A_minus',
        B_PLUS = 'B_plus',
        B = 'B',
        B_MINUS = 'B_minus',
        C_PLUS = 'C_plus',
        C = 'C',
        C_MINUS = 'C_minus',
        D = 'D',
    }
}
