// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type Distance = {
    amount: string
    /**
     * The estimated distance. Unit, `km` for kilometers, `mi` for miles
     *
     */
    unit: Distance.unit
}

export namespace Distance {
    /**
     * The estimated distance. Unit, `km` for kilometers, `mi` for miles
     *
     */
    export enum unit {
        KM = 'km',
        MI = 'mi',
        NM = 'nm',
    }
}
