// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * * `great_circle_distance` – Great-circle distance (as the crow flies)
 * * `great_circle_distance_x2` – Great-circle distance multiplied by two
 * * `sea_distance_algorithm` – our algorithm using known distances between ports
 * * `mapbox` – we used the Mapbox Matrix API
 * * `user_input` – the distance was provided to us directly
 * * `osrm` – we used Open Source Routing Machine, the OpenStreetMap Data Routing Engine
 * * `vessel_tracking` – we used the AIS data to track the vessel's route
 *
 */
export enum DistanceCalculationMethod {
    GREAT_CIRCLE_DISTANCE = 'great_circle_distance',
    GREAT_CIRCLE_DISTANCE_X2 = 'great_circle_distance_x2',
    SEA_DISTANCE_ALGORITHM = 'sea_distance_algorithm',
    MAPBOX = 'mapbox',
    USER_INPUT = 'user_input',
    OSRM = 'osrm',
    VESSEL_TRACKING = 'vessel_tracking',
}
