// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * * `great_circle_distance` – Great-circle distance (as the crow flies)
 * * `great_circle_distance_x2` – Great-circle distance multiplied by two
 * * `sea_distance_algorithm` – our algorithm using known distances between ports
 * * `inland_distance_algorithm` – our algorithm using OSM hydrographycal data
 * * `mapbox` – we used the Mapbox Matrix API
 * * `user_input` – the distance was provided to us directly
 * * `osrm` – we used Open Source Routing Machine, the OpenStreetMap Data Routing Engine
 * * `graphhopper` – we used GraphHopper routing engine
 * * `google_maps` - we used the Google Distance Matrix API
 * * `vessel_tracking` – we used the AIS data to track the vessel's route
 * * `carrier_schedule_stops` – we used the sea distance algorithm to calculate the distance
 * between the stops reported in the carrier schedule
 *
 */
export enum DistanceCalculationMethod {
    GREAT_CIRCLE_DISTANCE = 'great_circle_distance',
    GREAT_CIRCLE_DISTANCE_X2 = 'great_circle_distance_x2',
    SEA_DISTANCE_ALGORITHM = 'sea_distance_algorithm',
    INLAND_DISTANCE_ALGORITHM = 'inland_distance_algorithm',
    MAPBOX = 'mapbox',
    USER_INPUT = 'user_input',
    OSRM = 'osrm',
    GRAPHHOPPER = 'graphhopper',
    GOOGLE_MAPS = 'google_maps',
    VESSEL_TRACKING = 'vessel_tracking',
    CARRIER_SCHEDULE_STOPS = 'carrier_schedule_stops',
}
