// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * Details about the shipping method's electricity consumption used in the methodology for estimating emissions.
 *
 */
export type ElectricMethodMethodologyDetails = {
    /**
     * The vehicle's electricity consumption per tonne kilometre.
     *
     */
    electricityConsumption: {
        amount: string
        unit: ElectricMethodMethodologyDetails.unit
    }
}

export namespace ElectricMethodMethodologyDetails {
    export enum unit {
        K_WH_TKM = 'kWh/tkm',
    }
}
