// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { CurrencyCode } from './CurrencyCode.js'
import type { DistanceUnit } from './DistanceUnit.js'

export type EmissionFactorDenominatorUnit =
    | CurrencyCode
    | DistanceUnit
    | 'item'
    | 'MJ'
    | 'GJ'
    | 'guest*night'
    | 'room*night'
    | 'ha'
    | 'hour'
    | 'kWh'
    | 'kg'
    | 'kg*day'
    | 'km*year'
    | 'l'
    | 'Ml'
    | 'm*year'
    | 'm2'
    | 'm2*year'
    | 'm3'
    | 't*km'
    | 'person*km'
    | 't'
    | 'fte*working_hour'
    | 'container'
    | 'TEU*km'
