// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { EstimateIdempotencyKey } from './EstimateIdempotencyKey.js'
import type { EstimateMassWithWTWBreakdown } from './EstimateMassWithWTWBreakdown.js'
import type { Metadata } from './Metadata.js'

/**
 * A logistics emission estimate result. The value returned is in CO2e – it accounts for both CO2 and non-CO2 emissions.
 */
export type EmissionEstimateWithWTWBreakdown = {
    mass: EstimateMassWithWTWBreakdown
    metadata?: Metadata
    idempotencyKey?: EstimateIdempotencyKey
}
