// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { Mass } from './Mass.js'

/**
 * An emission estimate result. The value returned is in CO2e – it accounts for both CO2 and non-CO2 emissions.
 */
export type EmissionEstimate = {
    mass: Mass
}
