// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export enum EmissionFactorSource {
    EPA = 'epa',
    EXIOBASE = 'exiobase',
    ECOINVENT = 'ecoinvent',
    BEIS = 'beis',
    LUNE = 'lune',
    GLEC = 'glec',
    EMSA = 'emsa',
    CBAM = 'cbam',
}
