// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export enum EmissionFactorLogicalUnit {
    CURRENCY = 'currency',
    DISTANCE = 'distance',
    ITEM = 'item',
    TIME = 'time',
    AREA = 'area',
    VOLUME = 'volume',
    ENERGY = 'energy',
    MASS = 'mass',
    PERSON_TIME = 'person-time',
    PERSON_DISTANCE = 'person-distance',
    MASS_TIME = 'mass-time',
    MASS_DISTANCE = 'mass-distance',
    DISTANCE_TIME = 'distance-time',
    AREA_TIME = 'area-time',
    ROOM_TIME = 'room-time',
}
