// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { EmissionEstimate } from './EmissionEstimate.js'
import type { EstimateQuote } from './EstimateQuote.js'

/**
 * An emission estimate result including a quote
 */
export type EmissionEstimateResponse = EmissionEstimate & {
    /**
     * The emission calculation unique identifier
     */
    id: string
    quote: EstimateQuote
}
