// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { CurrencyCode } from './CurrencyCode.js'
import type { DistanceUnit } from './DistanceUnit.js'

export type EmissionFactorDenominatorUnit =
    | CurrencyCode
    | DistanceUnit
    | 'item'
    | 'MJ'
    | 'GJ'
    | 'guest*night'
    | 'room*night'
    | 'ha'
    | 'hour'
    | 'seconds'
    | 'kWh'
    | 'kWh ICV'
    | 'kWh LHV'
    | 'kWh HHV'
    | 'kWh SCV'
    | 'toe'
    | 'toe ICV'
    | 'toe HHV'
    | 'toe SCV'
    | 'GJ ICV'
    | 'GJ HHV'
    | 'GJ SCV'
    | 'MJ ICV'
    | 'kg'
    | 'kg*day'
    | 'km*year'
    | 'l'
    | 'Ml'
    | 'ml'
    | 'm*year'
    | 'cm2'
    | 'm2'
    | 'ha*year'
    | 'm2*year'
    | 'm3'
    | 'm3*km'
    | 't*km'
    | 'person*km'
    | 'person*month'
    | 'vehicle*km'
    | 'meal'
    | 't'
    | 'fte*working_hour'
    | 'TEU'
    | 'TEU*km'
    | 'p'
    | 'A4_sheets'
