// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * Account-unique identifier provided by the client.
 *
 * `idempotency_key` has two purposes:
 * 1. Clients can use `idempotency_key` to prevent duplicate estimates.
 * 2. Clients can use `idempotency_key` to reconcile estimates with entities on their system.
 *
 * If an estimate with the same `idempotency_key` already exists, the API returns
 * HTTP 409 Conflict with error code `estimate_idempotency_already_exists`.
 *
 */
export type EstimateIdempotencyKey = string
