// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { NullEnum } from './NullEnum.js'
import type { PollutantBreakdown } from './PollutantBreakdown.js'
import type { WTWBreakdown } from './WTWBreakdown.js'

export type EstimateMassBreakdowns = {
    /**
     * This property is `null` for any estimate created before 30/01/2025
     */
    wtwDetails: WTWBreakdown | NullEnum
    pollutants: NullEnum | PollutantBreakdown
}
