// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { AircraftConfiguration } from './AircraftConfiguration.js'
import type { NullEnum } from './NullEnum.js'

export type FlightNumberMethodResponse = {
    /**
     * Flight number in either ICAO or IATA format.
     *
     */
    flightNumber: string | null
    /**
     * Departure date of the flight.
     */
    departureOn: string | null
    aircraftConfiguration: AircraftConfiguration | NullEnum
}
