// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * Details about the parameters and calculations used in the methodology for estimating emissions by fuel.
 *
 */
export type FuelMethodologyDetails = {
    /**
     * The fuel's energy density.
     *
     * Energy density represents how much energy is stored in a litre of fuel.
     *
     */
    energyDensity: {
        amount: string
        unit: FuelMethodologyDetails.unit
    }
}

export namespace FuelMethodologyDetails {
    export enum unit {
        MJ_L = 'MJ/l',
    }
}
