// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * Unit of fuel consumption measurement.
 */
export enum FuelConsumptionUnit {
    L = 'l',
    KG = 'kg',
    KWH = 'kwh',
    GAL = 'gal',
}
