// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { GasWTWBreakdown } from './GasWTWBreakdown.js'

export type GasEmissions = {
    /**
     * Amount of CO₂ equivalent gas. All gas emissions are accounted here.
     */
    co2E: string
    /**
     * Amount of CO₂ gas.
     */
    co2?: string
    /**
     * Amount of methane gas.
     */
    methane?: string
    /**
     * Amount of nitrous oxide gas.
     */
    nitrousOxide?: string
    /**
     * Amount of other greenhouse gases.
     */
    other?: string
    wtwBreakdown?: GasWTWBreakdown
}
