// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * Emission factor has not been enabled. You may request access by emailing support@lune.co.
 *
 */
export enum GatedGasEmissions {
    EMISSION_FACTOR_GATED = 'emission_factor_gated',
}
