// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type HugeOilTankerSeaShippingMethod = {
    /**
     * Oil tanker >200 dwkt
     */
    vesselType: HugeOilTankerSeaShippingMethod.vessel_type
    fuel?: HugeOilTankerSeaShippingMethod.fuel
}

export namespace HugeOilTankerSeaShippingMethod {
    /**
     * Oil tanker >200 dwkt
     */
    export enum vessel_type {
        SEA_OIL_TANKER_HUGE = 'sea_oil_tanker_huge',
    }

    export enum fuel {
        HFO = 'HFO',
        MGO = 'MGO',
        LNG = 'LNG',
    }
}
