// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { IdentifiedVesselByIMOShippingMethod } from './IdentifiedVesselByIMOShippingMethod.js'
import type { IdentifiedVesselByNameShippingMethod } from './IdentifiedVesselByNameShippingMethod.js'

/**
 * This method uses either the vessel's IMO number or the vessel name in order to select an emission factor, falling back to trade lane emissions factors if provided.
 *
 */
export type IdentifiedVesselShippingMethod =
    | IdentifiedVesselByIMOShippingMethod
    | IdentifiedVesselByNameShippingMethod
