// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { TradeLane } from './TradeLane.js'
import type { VesselTrackingMethod } from './VesselTrackingMethod.js'

/**
 * This method uses the vessel's name to select an emission factors, falling back to trade lane emissions factors if provided. If the vessel name matches
 * multiple vessels with different IMO's or no vessel at all, the fallback is used.
 *
 */
export type IdentifiedVesselByNameShippingMethod =
    | {
          /**
           * The vessel's name, case-insensitive.
           *
           */
          vesselName: string
          vesselTracking?: VesselTrackingMethod
      }
    | {
          /**
           * The vessel's name.
           *
           */
          vesselName: string
          vesselType: IdentifiedVesselByNameShippingMethod.vessel_type
          /**
           * A container transport is either refrigerated or "dry" (not refrigerated). Dry transports
           * result in lower emissions.
           *
           */
          refrigerated?: boolean
          tradeLane?: TradeLane
      }

export namespace IdentifiedVesselByNameShippingMethod {
    export enum vessel_type {
        CONTAINER_SHIP = 'container_ship',
    }
}
