// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { TradeLane } from './TradeLane.js'
import type { VesselTrackingMethod } from './VesselTrackingMethod.js'

/**
 * This method uses the vessel's IMO number emission factors when found, falling back to trade lane emissions factors if provided.
 *
 */
export type IdentifiedVesselByIMOShippingMethod =
    | {
          /**
           * The vessel's [IMO number](https://en.wikipedia.org/wiki/IMO_number) *without* the `IMO` prefix.
           *
           */
          vesselImoNumber: string
          vesselTracking?: VesselTrackingMethod
      }
    | {
          /**
           * The vessel's [IMO number](https://en.wikipedia.org/wiki/IMO_number) *without* the `IMO` prefix.
           *
           */
          vesselImoNumber: string
          vesselType: IdentifiedVesselByIMOShippingMethod.vessel_type
          /**
           * A container transport is either refrigerated or "dry" (not refrigerated). Dry transports
           * result in lower emissions.
           *
           */
          refrigerated?: boolean
          tradeLane?: TradeLane
      }

export namespace IdentifiedVesselByIMOShippingMethod {
    export enum vessel_type {
        CONTAINER_SHIP = 'container_ship',
    }
}
