// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * International Commercial Term (Incoterms 2020) governing the shipment.
 *
 */
export enum Incoterm {
    EXW = 'exw',
    FCA = 'fca',
    CPT = 'cpt',
    CIP = 'cip',
    DAP = 'dap',
    DPU = 'dpu',
    DDP = 'ddp',
    FAS = 'fas',
    FOB = 'fob',
    CFR = 'cfr',
    CIF = 'cif',
}
