// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { EmissionStandardRegion } from './EmissionStandardRegion.js'
import type { NullEnum } from './NullEnum.js'
import type { RoadEmissionStandard } from './RoadEmissionStandard.js'
import type { RoadVehicleType } from './RoadVehicleType.js'
import type { ShippingCountryCode } from './ShippingCountryCode.js'

export type InferenceDetails = {
    /**
     * The trade lane Lune has inferred as most likely for the shipment's route.
     */
    tradeLaneFromRoute?: string
    /**
     * Inferred rail transport type based on the shipment's route.
     */
    railTypeFromRoute: {
        railType: InferenceDetails.rail_type
        sourceCountry: string
        destinationCountry: string
    } | null
    /**
     * The road emission standard trade has inferred via country information in the shipment's route.
     */
    roadEmissionStandard: {
        value: RoadEmissionStandard
        from: InferenceDetails.from
        /**
         * Inferred source country code
         */
        sourceCountryCode: ShippingCountryCode | NullEnum
        /**
         * Inferred destination country code
         */
        destinationCountryCode: ShippingCountryCode | NullEnum
        /**
         * Inferred source country region, present when region information was used to infer the standard
         */
        sourceRegion: EmissionStandardRegion | NullEnum
        /**
         * Inferred destination country region, present when region information was used to infer the standard
         */
        destinationRegion: EmissionStandardRegion | NullEnum
    } | null
    /**
     * The truck type infered via the shipment's route and shipment mass.
     */
    roadTruckType: {
        value: RoadVehicleType
        isInternationalShipment: boolean
    } | null
}

export namespace InferenceDetails {
    export enum rail_type {
        ELECTRIC_FREIGHT_TRAIN = 'electric_freight_train',
        DIESEL_FREIGHT_TRAIN = 'diesel_freight_train',
    }

    export enum from {
        SOURCE = 'source',
        DESTINATION = 'destination',
        BOTH = 'both',
    }
}
