// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * Use to distinguish confirmed shipments from quotes. Defaults to `false` when omitted. Can be updated at any point.
 *
 * This property must be formatted as RFC 3339, section 5.6 timestamp.
 *
 * Examples:
 * * 2023-12-01T12:30:30.000Z
 * * 2023-12-01T12:30:30Z
 * * 2023-12-01T11:30:30+01.00
 *
 */
export type IsShipment = boolean
