// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * Use to distinguish confirmed transaction documents from quotes or forecasts. Defaults to `false` when omitted. Can be updated at any point.
 *
 * When `true`, the estimate represents an actual transaction document for purchased goods and services and will be included in Lune analytics.
 *
 */
export type IsTransactionDocument = boolean
