// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { CargoType } from './CargoType.js'
import type { Mass } from './Mass.js'

/**
 * Provide the shipment mass using either `mass` (in grams, kilograms, or tonnes) or `containers` (in Twenty-foot Equivalent Units, or TEUs).
 *
 * When using `containers`, you can optionally include `mass` and `cargo_type` for more accurate estimates.
 *
 */
export type Load =
    | {
          mass: Mass
      }
    | {
          containers: string
          cargoType?: CargoType
          mass?: Mass
      }
