// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export enum LoadConversionMethod {
    USER_PROVIDED_CARGO_TYPE = 'user_provided_cargo_type',
    AVERAGE_CARGO_TYPE = 'average_cargo_type',
}
