// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type LogisticsActivity = {
    /**
     * The transport activity being measured.
     *
     * For example, if you are measuring a truck transporting 4 tonnes of goods that traveled 15.25 kilometers, the activity value would be 61 t*km
     *
     */
    value: string
    /**
     * The units of the transport activity being measured.
     *
     */
    unit: LogisticsActivity.unit
}

export namespace LogisticsActivity {
    /**
     * The units of the transport activity being measured.
     *
     */
    export enum unit {
        T_KM = 't*km',
        T = 't',
    }
}
