// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type LogisticsIntensity = {
    amount: string
    /**
     * Carbon intensity in CO2 equivalents.
     *
     * Example: `t_per_tkm` for tonnes of CO2 equivalent per tonne-kilometre,
     *
     */
    unit: LogisticsIntensity.unit
}

export namespace LogisticsIntensity {
    /**
     * Carbon intensity in CO2 equivalents.
     *
     * Example: `t_per_tkm` for tonnes of CO2 equivalent per tonne-kilometre,
     *
     */
    export enum unit {
        T_PER_TKM = 't_per_tkm',
        KG_PER_TKM = 'kg_per_tkm',
        G_PER_TKM = 'g_per_tkm',
        MG_PER_TKM = 'mg_per_tkm',
        T_PER_T = 't_per_t',
        KG_PER_T = 'kg_per_t',
        G_PER_T = 'g_per_t',
        MG_PER_T = 'mg_per_t',
    }
}
