// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * Logistics sites are locations where goods are stored, repacked and distributed.
 *
 */
export enum LogisticsSiteMethod {
    MARITIME_CONTAINER_TERMINAL = 'maritime_container_terminal',
    MARITIME_CONTAINER_TERMINAL_AMBIENT = 'maritime_container_terminal_ambient',
    MARITIME_CONTAINER_TERMINAL_CHILLED = 'maritime_container_terminal_chilled',
    TRANSHIPMENT_SITE_AMBIENT = 'transhipment_site_ambient',
    TRANSHIPMENT_SITE_CHILLED = 'transhipment_site_chilled',
    TRANSHIPMENT_SITE_MIXED = 'transhipment_site_mixed',
    STORAGE_AND_TRANSHIPMENT_AMBIENT = 'storage_and_transhipment_ambient',
    STORAGE_AND_TRANSHIPMENT_CHILLED = 'storage_and_transhipment_chilled',
    STORAGE_AND_TRANSHIPMENT_MIXED = 'storage_and_transhipment_mixed',
    WAREHOUSE_AMBIENT = 'warehouse_ambient',
    WAREHOUSE_CHILLED = 'warehouse_chilled',
    WAREHOUSE_MIXED = 'warehouse_mixed',
    LIQUID_BULK_TERMINALS_AMBIENT = 'liquid_bulk_terminals_ambient',
    LIQUID_BULK_TERMINALS_MIXED = 'liquid_bulk_terminals_mixed',
}
