// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * Unit, `t` for tonne, `kg` for kilogram, `g` for gram
 */
export enum MassUnit {
    G = 'g',
    KG = 'kg',
    T = 't',
}
