// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { OptionalMerchantViaCategory } from './OptionalMerchantViaCategory.js'
import type { OptionalMerchantViaSearch } from './OptionalMerchantViaSearch.js'

export type OptionalMerchant = OptionalMerchantViaCategory | OptionalMerchantViaSearch
