// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type OrderByQuantityProperties = {
    /**
     * Requested quantity of CO2 offsets to purchase in tonnes.
     */
    requestedQuantity: string
    /**
     * Requested value of CO2 offsets to purchase in the account's currency.
     */
    requestedValue: string | null
    /**
     * The emission calculation unique identifier
     */
    estimateId: string | null
}
