// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { BundleSelectionRequest } from './BundleSelectionRequest.js'
import type { Mass } from './Mass.js'
import type { MassUnit } from './MassUnit.js'

/**
 * Order by Quantity details
 */
export type OrderQuoteByQuantityWithBundlePercentage = {
    /**
     * Mass of CO2 offsets to purchase
     */
    mass: Mass
    bundleSelection?: BundleSelectionRequest
    /**
     * Selects to which precision to truncate the quantities assigned to each bundle.
     */
    quantityTrunc?: MassUnit
}
