// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { ClientAccountWithAnalyticSummary } from './ClientAccountWithAnalyticSummary.js'
import type { PaginatedBase } from './PaginatedBase.js'

export type PaginatedClientAccounts = PaginatedBase & {
    /**
     * An array of Client Account objects
     *
     * Part of a paginated response.
     *
     */
    data: Array<ClientAccountWithAnalyticSummary>
}
