// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { PaginatedBase } from './PaginatedBase.js'
import type { Shipment } from './Shipment.js'

export type PaginatedShipments = PaginatedBase & {
    /**
     * An array of Shipment objects ordered by creation date descending.
     *
     * Part of a paginated response.
     *
     */
    data: Array<Shipment>
    /**
     * Total number of shipments matching the active filters.
     *
     */
    total: {
        all: number
        withCo2E: number
        withoutCo2E: number
    }
}
