// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { EmissionFactor } from './EmissionFactor.js'
import type { PaginatedBase } from './PaginatedBase.js'

export type PaginatedEmissionFactors = PaginatedBase & {
    /**
     * An array of Emission Factor objects, ordered by best match.
     *
     * Part of a paginated response.
     *
     */
    data: Array<EmissionFactor>
}
