// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type PaginatedBase = {
    /**
     * Whether or not there are more elements available after this set.
     *
     * If false, this set comprises the end of the array.
     *
     * Part of a paginated response.
     *
     */
    hasMore: boolean
    /**
     * The cursor value to be used as the after parameter for fetching the next page of results.
     *
     * `null` if `has_more` is `false`.
     *
     */
    nextCursor: string | null
}
