// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * Providing null on a property will result in clearing the existing value (if present).
 *
 */
export type PartialUpdateAccountRequest = {
    /**
     * The account name.
     */
    name?: string
    /**
     * The account beneficiary.
     */
    beneficiary?: string | null
    /**
     * The bundle portfolio unique identifier.
     */
    bundlePortfolioId?: string | null
}
