// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { Distance } from './Distance.js'
import type { EmissionFactorWithGasEmissions } from './EmissionFactorWithGasEmissions.js'
import type { EstimateMass } from './EstimateMass.js'
import type { NullEnum } from './NullEnum.js'
import type { ResolvedPassengerTransportationEmissionEstimateLegs } from './ResolvedPassengerTransportationEmissionEstimateLegs.js'

export type PassengerTransportationLegEmissionEstimate = {
    mass: EstimateMass
    distance?: Distance
    /**
     * This property is `null` for any estimate created before 01/12/2024
     */
    emissionFactor?: EmissionFactorWithGasEmissions | NullEnum
    /**
     * If the input method results in multiple legs being detected, each leg will be
     * calculated and shown separately.
     *
     */
    resolvedLegs?: ResolvedPassengerTransportationEmissionEstimateLegs | NullEnum
}
