// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { EmissionEstimate } from './EmissionEstimate.js'
import type { EstimateQuote } from './EstimateQuote.js'
import type { PassengerTransportationEstimateRequest } from './PassengerTransportationEstimateRequest.js'
import type { PassengerTransportationLegEmissionEstimate } from './PassengerTransportationLegEmissionEstimate.js'
import type { PassengerTransportationTravelledAt } from './PassengerTransportationTravelledAt.js'

/**
 * An emission estimate result for passenger transport involving multiple legs.
 *
 * Lune's API returns both the total emissions and per-leg emissions (in the `legs`
 * property).
 *
 * The ordering of the legs in the estimate is the same as the ordering of the inputs.
 *
 * An error with estimating any of the legs will result in the whole estimation process
 * failing completely (we don't provide partial estimates in light of a failure).
 *
 */
export type PassengerTransportationEmissionEstimate = EmissionEstimate & {
    /**
     * The emission calculation unique identifier
     */
    id: string
    legs: Array<PassengerTransportationLegEmissionEstimate>
    quote: EstimateQuote
    request: PassengerTransportationEstimateRequest
    /**
     * When true, the emission estimate refers to an actual passenger transportation journey and will be included in Lune analytics and can be included in any CO2 emissions reporting.
     *
     * This property exists to distinguish generic estimates, quotes or forecasts from actual passenger transportation that has occurred.
     *
     */
    isPassengerTransportation?: boolean
    passengerTransportationTravelledAt?: PassengerTransportationTravelledAt
}
