// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type PendingShipmentBatch = {
    /**
     * Batch identifier.
     */
    id: string
    /**
     * Batch processing status.
     */
    status: PendingShipmentBatch.status
}

export namespace PendingShipmentBatch {
    /**
     * Batch processing status.
     */
    export enum status {
        PENDING = 'pending',
    }
}
