// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type PendingCalculationBatch = {
    /**
     * Calculation batch identifier.
     */
    id: string
    status: PendingCalculationBatch.status
    /**
     * Number of shipments requested for calculation.
     */
    shipmentCount: number
    /**
     * Timestamp when the calculation batch was created.
     */
    createdAt: string
}

export namespace PendingCalculationBatch {
    export enum status {
        PENDING = 'pending',
    }
}
