// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { PollutantEmissions } from './PollutantEmissions.js'

/**
 * Individual pollutants that are part of the estimated emissions.
 *
 * * `nox` - Nitrogen oxides
 * * `nmhc` - Non-methane hydrocarbons
 * * `so2` - Sulfur dioxide
 * * `co2` - Carbon dioxide
 * * `pm` - Particulate matter
 *
 */
export type PollutantBreakdown = {
    nox: PollutantEmissions
    nmhc: PollutantEmissions
    so2: PollutantEmissions
    co2: PollutantEmissions
    pm: PollutantEmissions
}
