// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { CalculationBatchRowResult } from './CalculationBatchRowResult.js'

export type ProcessingCalculationBatch = {
    /**
     * Calculation batch identifier.
     */
    id: string
    status: ProcessingCalculationBatch.status
    /**
     * Number of shipments requested for calculation.
     */
    shipmentCount: number
    /**
     * Timestamp when the calculation batch was created.
     */
    createdAt: string
    /**
     * Number of rows successfully completed so far.
     */
    successCount: number
    /**
     * Number of rows that have failed so far.
     */
    failedCount: number
    /**
     * Results for the first requested shipments, in request order. This
     * array has fewer items than `shipment_count` while processing.
     *
     */
    results: Array<CalculationBatchRowResult>
}

export namespace ProcessingCalculationBatch {
    export enum status {
        PROCESSING = 'processing',
    }
}
