// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type ProcessedCalculationBatchWithError = {
    /**
     * Calculation batch identifier.
     */
    id: string
    status: ProcessedCalculationBatchWithError.status
    /**
     * Number of shipments requested for calculation.
     */
    shipmentCount: number
    /**
     * Timestamp when the calculation batch was created.
     */
    createdAt: string
    /**
     * Batch-level calculation error, when row processing did not run.
     */
    batchError: string
}

export namespace ProcessedCalculationBatchWithError {
    export enum status {
        PROCESSED = 'processed',
    }
}
