// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type ProcessedShipmentBatchWithError = {
    /**
     * Batch identifier.
     */
    id: string
    /**
     * Batch processing status.
     */
    status: ProcessedShipmentBatchWithError.status
    /**
     * Batch-level processing error, when row processing did not run.
     */
    batchError: string
}

export namespace ProcessedShipmentBatchWithError {
    /**
     * Batch processing status.
     */
    export enum status {
        PROCESSED = 'processed',
    }
}
