// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { Media } from './Media.js'
import type { Registry } from './Registry.js'

export type ProjectSummary = {
    /**
     * The projects's unique identifier
     */
    id: string
    /**
     * The project's name
     */
    name: string
    /**
     * The project's short name. May coincide with name.
     */
    shortName: string
    /**
     * Project slug
     */
    slug: string
    /**
     * Project description
     */
    description: string
    /**
     * The project's offset type, eg Forest conservation, Afforestation, Direct Air Capture
     */
    projectType: string
    registryName: Registry
    /**
     * A link to the registry's project details page.
     */
    registryLink: string | null
    /**
     * Latitude
     */
    latitude: number
    /**
     * Logitude
     */
    longitude: number
    /**
     * The project's country
     */
    countryName: string
    /**
     * The project's 3 character country code
     */
    countryCode: string
    /**
     * The project's region
     */
    region: string | null
    /**
     * A project logo image URL
     */
    logo: string | null
    /**
     * A project image URL
     */
    primaryImage: string | null
    /**
     * A project thumbnail image URL
     */
    thumbnailImage: string | null
    /**
     * Project results
     */
    results: Array<string> | null
    /**
     * UN Sustainable Development Goals.
     *
     * Each number in the array represent one UN Sustainable Development Goal. See https://sdgs.un.org/goals.
     *
     */
    unSdg: Array<number> | null
    /**
     * Disabled projects do not get allocated to orders
     *
     */
    disabled: boolean
    /**
     * A list of images and videos belonging to the project.
     */
    media: Array<Media>
    /**
     * Project’s crediting period start date.
     */
    creditingStartDate: string | null
    /**
     * Project’s crediting period end date.
     */
    creditingEndDate: string | null
    /**
     * Date the project was registered in the registry.
     */
    registrationDate: string | null
    /**
     * The standard followed to assure that a carbon offset project delivers on carbon reduction or removal.
     */
    protocol: Array<string> | null
    /**
     * Detailed application of the broader principles set out in the protocol.
     */
    methodology: string | null
    /**
     * Expected duration of the carbon storage (carbon removal projects only).
     */
    durability: string | null
    /**
     * Any additional standards the project meets.
     */
    additionalStandardsMet: Array<string> | null
    /**
     * Independent entity assessing compliance of carbon projects with protocol and methodology.
     */
    verifyingBody: string | null
    /**
     * Mitigation plan for the risk of reversal.
     */
    riskOfReversal: string | null
    /**
     * Mitigation plan for the risk of predicted reductions or removals not occurring.
     */
    riskOfPredictedEmissions: string | null
    /**
     * Estimated average annual reductions or removals.
     */
    avgAnnualEmissionReductions: string | null
}
