// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type RawDistance = {
    amount: string
    /**
     * A raw estimate of distance before GLEC required Distance Adjustment Factors are applied.
     */
    unit: RawDistance.unit
}

export namespace RawDistance {
    /**
     * A raw estimate of distance before GLEC required Distance Adjustment Factors are applied.
     */
    export enum unit {
        KM = 'km',
        MI = 'mi',
        NM = 'nm',
    }
}
