// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * The project's Verification Standard Entity name or equivalent organization.
 */
export enum Registry {
    AMERICAN_CARBON_REGISTRY = 'American Carbon Registry',
    VERRA = 'Verra',
    PURO_EARTH = 'Puro.earth',
    GOLD_STANDARD = 'Gold Standard',
    CLIMATE_ACTION_RESERVE = 'Climate Action Reserve',
    WOODLAND_CARBON_CODE = 'Woodland Carbon Code',
    ACCU = 'ACCU',
    __EMPTY__ = '',
}
