// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * Controls how geographical constraints are interpreted and if a fallback is performed.
 * For example, how fields like `country_code` and `region` are interpreted.
 *
 * * `never` (the default) means no fallback is performed and only emission
 * factors that match the specified geographical area are returned.
 * * `always` means the emission factors for related geographic areas are unconditionally included
 * in the results.
 *
 */
export enum RegionFallback {
    NEVER = 'never',
    ALWAYS = 'always',
}
