// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * Describes the road's topology.
 */
export enum RoadGradient {
    FLAT = 'flat',
    HILLY = 'hilly',
    MOUNTAINOUS = 'mountainous',
}
