// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export enum RoadVehicleType {
    TRUCK_GENERIC_VAN = 'truck_generic_van',
    TRUCK_RIGID_7_5T = 'truck_rigid_7_5t',
    TRUCK_RIGID_12T = 'truck_rigid_12t',
    TRUCK_RIGID_20T = 'truck_rigid_20t',
    TRUCK_RIGID_26T = 'truck_rigid_26t',
    TRUCK_RIGID_32T = 'truck_rigid_32t',
    TRUCK_ARTICULATED_34T = 'truck_articulated_34t',
    TRUCK_ARTICULATED_40T = 'truck_articulated_40t',
    TRUCK_ARTICULATED_44T = 'truck_articulated_44t',
    TRUCK_ARTICULATED_60T = 'truck_articulated_60t',
    TRUCK_ARTICULATED_72T = 'truck_articulated_72t',
}
