// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * Situation describes the driving environment and road condition.
 */
export enum RoadSituation {
    CITY_URBAN_FREEFLOW = 'city_urban_freeflow',
    MOTORWAY_URBAN_FREEFLOW = 'motorway_urban_freeflow',
    MOTORWAY_RURAL_FREEFLOW = 'motorway_rural_freeflow',
    CITY_URBAN_HEAVY_TRAFFIC = 'city_urban_heavy_traffic',
    CITY_URBAN_STOP_AND_GO = 'city_urban_stop_and_go',
    MOTORWAY_URBAN_HEAVY_TRAFFIC = 'motorway_urban_heavy_traffic',
    MOTORWAY_URBAN_STOP_AND_GO = 'motorway_urban_stop_and_go',
    MOTORWAY_RURAL_HEAVY_TRAFFIC = 'motorway_rural_heavy_traffic',
    MOTORWAY_RURAL_STOP_AND_GO = 'motorway_rural_stop_and_go',
    ARTERIAL_ROAD_RURAL_FREEFLOW = 'arterial_road_rural_freeflow',
    ARTERIAL_ROAD_RURAL_HEAVY_TRAFFIC = 'arterial_road_rural_heavy_traffic',
    ARTERIAL_ROAD_RURAL_STOP_AND_GO = 'arterial_road_rural_stop_and_go',
}
