// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { RoadEmissionStandard } from './RoadEmissionStandard.js'
import type { RoadEmptyRunsFactor } from './RoadEmptyRunsFactor.js'
import type { RoadFuel } from './RoadFuel.js'
import type { RoadGradient } from './RoadGradient.js'
import type { RoadLoadFactor } from './RoadLoadFactor.js'
import type { RoadSituation } from './RoadSituation.js'
import type { RoadVehicleType } from './RoadVehicleType.js'

/**
 * Calculate emissions for road vehicles based on input parameters such as vehicle type, fuel type, load factor, empty runs factor, etc.
 *
 */
export type RoadShippingMethod = {
    /**
     * Vehicle type used for shipping. Use the `truck` method to have Lune infer the type of truck most likely used
     *
     */
    vehicleType: RoadVehicleType | 'truck'
    fuel: RoadFuel
    /**
     * Describes the road's topology.
     *
     * If not defined, the most representative value is chosen.
     *
     */
    gradient?: RoadGradient
    /**
     * Measure of how fully a vehicle is utilising its cargo capacity.
     *
     * If not defined, the most representative value is chosen.
     *
     */
    loadFactor?: RoadLoadFactor
    /**
     * Empty runs factor measures the proportion of a vehicle's travel that occurs without carrying any cargo.
     *
     * If not defined, the most representative value is chosen.
     *
     */
    emptyRunsFactor?: RoadEmptyRunsFactor
    /**
     * Situation describes the driving environment and road condition.
     *
     * If not defined, the most representative value is chosen.
     *
     */
    situation?: RoadSituation
    /**
     * The vehicle's emission standard for pollution.
     *
     * If not defined, the most representative value is chosen.
     *
     */
    emissionStandard?: RoadEmissionStandard
    /**
     * The shipment is refrigerated or "dry" (not refrigerated).
     * Dry shipments result in lower emissions.
     *
     */
    refrigerated?: boolean
}
