// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { RoadEmissionStandard } from './RoadEmissionStandard.js'
import type { RoadEmptyRunsFactor } from './RoadEmptyRunsFactor.js'
import type { RoadGradient } from './RoadGradient.js'
import type { RoadLoadFactor } from './RoadLoadFactor.js'
import type { RoadSituation } from './RoadSituation.js'

/**
 * Calculate emissions for road vehicles based on input parameters such as vehicle type, fuel type, load factor, empty runs factor, etc.
 *
 */
export type RoadShippingMethod = {
    vehicleType: RoadShippingMethod.vehicle_type
    fuel: RoadShippingMethod.fuel
    /**
     * Describes the road's topology.
     *
     * If not defined, the most representative value is chosen.
     *
     */
    gradient?: RoadGradient
    /**
     * Measure of how fully a vehicle is utilising its cargo capacity.
     *
     * If not defined, the most representative value is chosen.
     *
     */
    loadFactor?: RoadLoadFactor
    /**
     * Empty runs factor measures the proportion of a vehicle's travel that occurs without carrying any cargo.
     *
     * If not defined, the most representative value is chosen.
     *
     */
    emptyRunsFactor?: RoadEmptyRunsFactor
    /**
     * Situation describes the driving environment and road condition.
     *
     * If not defined, the most representative value is chosen.
     *
     */
    situation?: RoadSituation
    /**
     * The vehicle's emission standard for pollution.
     *
     * If not defined, the most representative value is chosen.
     *
     */
    emissionStandard?: RoadEmissionStandard
}

export namespace RoadShippingMethod {
    export enum vehicle_type {
        TRUCK_GENERIC_VAN = 'truck_generic_van',
        TRUCK_RIGID_7_5T = 'truck_rigid_7_5t',
        TRUCK_RIGID_12T = 'truck_rigid_12t',
        TRUCK_RIGID_20T = 'truck_rigid_20t',
        TRUCK_RIGID_26T = 'truck_rigid_26t',
        TRUCK_RIGID_32T = 'truck_rigid_32t',
        TRUCK_ARTICULATED_34T = 'truck_articulated_34t',
        TRUCK_ARTICULATED_40T = 'truck_articulated_40t',
    }

    export enum fuel {
        GASOLINE = 'gasoline',
        DIESEL = 'diesel',
        _99_DIESEL_1_BIODIESEL = '99_diesel_1_biodiesel',
        _98_DIESEL_2_BIODIESEL = '98_diesel_2_biodiesel',
        _95_DIESEL_5_BIODIESEL = '95_diesel_5_biodiesel',
        _93_DIESEL_7_BIODIESEL = '93_diesel_7_biodiesel',
        _90_DIESEL_10_BIODIESEL = '90_diesel_10_biodiesel',
        _80_DIESEL_20_BIODIESEL = '80_diesel_20_biodiesel',
        _50_DIESEL_50_BIODIESEL = '50_diesel_50_biodiesel',
        ETHANOL_FROM_CORN = 'ethanol_from_corn',
        HVO_FROM_TALLOW = 'hvo_from_tallow',
        LPG = 'lpg',
        CNG = 'cng',
    }
}
