// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * The vehicle's fuel.
 */
export enum RoadFuel {
    GASOLINE = 'gasoline',
    DIESEL = 'diesel',
    _99_DIESEL_1_BIODIESEL = '99_diesel_1_biodiesel',
    _98_DIESEL_2_BIODIESEL = '98_diesel_2_biodiesel',
    _95_DIESEL_5_BIODIESEL = '95_diesel_5_biodiesel',
    _93_DIESEL_7_BIODIESEL = '93_diesel_7_biodiesel',
    _90_DIESEL_10_BIODIESEL = '90_diesel_10_biodiesel',
    _80_DIESEL_20_BIODIESEL = '80_diesel_20_biodiesel',
    _50_DIESEL_50_BIODIESEL = '50_diesel_50_biodiesel',
    ETHANOL_FROM_CORN = 'ethanol_from_corn',
    HVO_FROM_TALLOW = 'hvo_from_tallow',
    LPG = 'lpg',
    CNG = 'cng',
}
