// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * Situation describes the driving environment and road condition.
 */
export enum RoadSituation {
    CITY_URBAN_FREEFLOW = 'city_urban_freeflow',
    MOTORWAY_URBAN_FREEFLOW = 'motorway_urban_freeflow',
    MOTORWAY_RURAL_FREEFLOW = 'motorway_rural_freeflow',
}
