// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * The vehicle's emission standard for pollution.
 */
export enum RoadEmissionStandard {
    EURO1 = 'euro1',
    EURO2 = 'euro2',
    EURO3 = 'euro3',
    EURO4 = 'euro4',
    EURO5 = 'euro5',
    EURO6 = 'euro6',
}
