// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type RoRoSeaShippingMethod = {
    vesselType: RoRoSeaShippingMethod.vessel_type
    fuel?: RoRoSeaShippingMethod.fuel
    /**
     * Vessel sizes:
     * * `freight_only` - Ro-Ro 5-10 dwkt
     * * `truck_and_trailer` - Ro-Ro <5 dwkt
     * * `trailer_only` - Ro-Ro 5-10 dwkt
     *
     */
    load?: RoRoSeaShippingMethod.load
}

export namespace RoRoSeaShippingMethod {
    export enum vessel_type {
        SEA_RORO = 'sea_roro',
    }

    export enum fuel {
        HFO = 'HFO',
        MGO = 'MGO',
    }

    /**
     * Vessel sizes:
     * * `freight_only` - Ro-Ro 5-10 dwkt
     * * `truck_and_trailer` - Ro-Ro <5 dwkt
     * * `trailer_only` - Ro-Ro 5-10 dwkt
     *
     */
    export enum load {
        FREIGHT_ONLY = 'freight_only',
        TRUCK_AND_TRAILER = 'truck_and_trailer',
        TRAILER_ONLY = 'trailer_only',
    }
}
