// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { CalculatedRouteLocation } from './CalculatedRouteLocation.js'

export type RouteInferenceExplanation = {
    /**
     * The provided source location was detected to be within a small radius of the closest known transfer point.
     * Your route begins at this point.
     *
     */
    snappedSourceToKnownLocation?: CalculatedRouteLocation
    /**
     * The provided destination location was detected to be within a small radius of the closest known transfer point.
     * Your route ends at this point.
     *
     */
    snappedDestinationToKnownLocation?: CalculatedRouteLocation
    /**
     * The provided source location is sufficiently far from any known transfer point.
     * Lune has inferred a road transportation leg from your provided source to the closest known transfer point.
     *
     */
    inferredSourceTransferPoint?: CalculatedRouteLocation
    /**
     * The provided destination location is sufficiently far from any known transfer point.
     * Lune has inferred a road transportation leg from the closest known transfer point to your provided destination.
     *
     */
    inferredDestinationTransferPoint?: CalculatedRouteLocation
    /**
     * Lune has detected that your provided flight number has resolved into two or more legs.
     */
    resolvedFromFlightNumber?: string
}
