// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { NullEnum } from './NullEnum.js'

/**
 * Details about the parameters and calculations used in the methodology for estimating sea freight emissions.
 *
 */
export type SeaMethodologyDetails = {
    /**
     * Estimate of the fuel consumed on the sea voyage, measured in tonnes.
     */
    seaVoyageFuelConsumedTonnes: number
    /**
     * The estimated average crusising speed of the vessel, in knots.
     *
     */
    vesselCruisingSpeedKnots: number
    /**
     * The source of the average vessel cruising speed. Can be either from:
     * - IMO published average for the vessel's TEU class
     * - Averaged cruising speed for the specific vessel calculated from AIS data
     *
     */
    vesselCruisingSpeedSource: SeaMethodologyDetails.vessel_cruising_speed_source
    /**
     * The estimated time over which the voyage took place, in hours.
     *
     */
    voyageTimeHours: number
    /**
     * The calculated emissions (tCO2e) per TEU.
     *
     */
    voyageEmissionsPerTeu: number
    /**
     * Estimate of the fuel consumed by refrigerating the shipment on the sea  voyage,
     * measured in tonnes. Null if the leg was not refrigerated.
     *
     */
    refrigerationFuelConsumedTonnes: number | NullEnum
}

export namespace SeaMethodologyDetails {
    /**
     * The source of the average vessel cruising speed. Can be either from:
     * - IMO published average for the vessel's TEU class
     * - Averaged cruising speed for the specific vessel calculated from AIS data
     *
     */
    export enum vessel_cruising_speed_source {
        AVERAGE_FOR_VESSEL_CLASS = 'average_for_vessel_class',
        AIS = 'ais',
        AIS_VOYAGE_SPECIFIC = 'ais_voyage_specific',
    }
}
