// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * Details about the parameters and calculations used in the methodology for estimating sea freight emissions.
 *
 */
export type SeaMethodologyDetails = {
    /**
     * Estimate of the fuel consumed on the sea voyage, measured in tonnes.
     */
    seaVoyageFuelConsumedTonnes: number
    /**
     * The estimated average crusising speed of the vessel, in knots.
     *
     */
    vesselCruisingSpeedKnots: number
    /**
     * The estimated time over which the voyage took place, in hours.
     *
     */
    voyageTimeHours: number
    /**
     * The calculated emissions (tCO2e) per TEU.
     *
     */
    voyageEmissionsPerTeu: number
}
