// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * Tour information for grouping related shipments (e.g. milkrun).
 */
export type ShipmentTourResponse = {
    /**
     * Client-side tour identifier.
     */
    id: string | null
    /**
     * Whether the vehicle returns to base after the tour.
     */
    returnToBase: boolean | null
}
