// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { Mass } from './Mass.js'

/**
 * Provide the shipment weight using either `mass` (in grams, kilograms, or tonnes) or `containers` (in Twenty-foot Equivalent Units, or TEUs).
 *
 * When using `containers`, you can optionally include `mass` and `cargo_type` for more accurate estimates.
 *
 */
export type Shipment =
    | {
          mass: Mass
      }
    | {
          containers: string
          /**
           * Specify the weight of cargo in the container. If omitted, `average` is used by default.
           *
           * Each type applies a different conversion to mass for emissions estimation. See [TEU conversion table](https://docs.lune.co/general-concepts/logistics-methodology#13-cargo-weight) for details.
           *
           */
          cargoType?: Shipment.cargo_type
          mass?: Mass
      }

export namespace Shipment {
    /**
     * Specify the weight of cargo in the container. If omitted, `average` is used by default.
     *
     * Each type applies a different conversion to mass for emissions estimation. See [TEU conversion table](https://docs.lune.co/general-concepts/logistics-methodology#13-cargo-weight) for details.
     *
     */
    export enum cargo_type {
        LIGHTWEIGHT = 'lightweight',
        AVERAGE = 'average',
        HEAVYWEIGHT = 'heavyweight',
        CONTAINER_ONLY = 'container_only',
    }
}
