// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { Mass } from './Mass.js'
import type { ShipmentContainerResponse } from './ShipmentContainerResponse.js'
import type { Volume } from './Volume.js'

/**
 * Cargo load details for a shipment leg.
 */
export type ShipmentLoadResponse = {
    weight: Mass | null
    volume: Volume | null
    /**
     * Number of pieces in the load.
     */
    pieceCount: number | null
    chargeableWeight: Mass | null
    containers: Array<ShipmentContainerResponse> | null
}
