// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { ContainerLoadType } from './ContainerLoadType.js'
import type { ContainerSizeType } from './ContainerSizeType.js'
import type { Mass } from './Mass.js'

/**
 * Details of a shipping container.
 */
export type ShipmentContainer = {
    type?: ContainerSizeType
    /**
     * TEU equivalent of the container.
     */
    teu?: string
    loadType?: ContainerLoadType
    containerEmptyMass?: Mass
}
