// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { FuelConsumption } from './FuelConsumption.js'
import type { Mass } from './Mass.js'
import type { RoadEmissionStandard } from './RoadEmissionStandard.js'
import type { RoadFuel } from './RoadFuel.js'
import type { RoadGradient } from './RoadGradient.js'
import type { RoadSituation } from './RoadSituation.js'
import type { RoadVehicleType } from './RoadVehicleType.js'

/**
 * Road transport method with shipment-specific reporting fields such as
 * vehicle identification and fuel consumption.
 *
 */
export type ShipmentRoadMethod = {
    /**
     * Vehicle type used for shipping.
     *
     */
    vehicleType: RoadVehicleType | 'truck'
    fuel: RoadFuel
    /**
     * Describes the road's topology.
     *
     */
    gradient?: RoadGradient
    /**
     * Situation describes the driving environment and road condition.
     *
     */
    situation?: RoadSituation
    /**
     * The vehicle's emission standard for pollution.
     *
     */
    emissionStandard?: RoadEmissionStandard
    /**
     * The shipment is refrigerated or "dry" (not refrigerated).
     *
     */
    refrigerated?: boolean
    /**
     * License plate number of the truck.
     */
    truckLicensePlate?: string
    /**
     * License plate number of the trailer.
     */
    trailerLicensePlate?: string
    /**
     * Vehicle Identification Number.
     */
    vin?: string
    /**
     * Type of road (e.g. highway, urban).
     */
    roadType?: string
    /**
     * Gross vehicle weight rating.
     */
    grossVehicleWeightRating?: Mass
    /**
     * Primary fuel consumption for this leg.
     */
    fuelConsumption?: FuelConsumption
    /**
     * Secondary fuel consumption (e.g. electric portion of a hybrid).
     */
    secondaryFuelConsumption?: FuelConsumption
    /**
     * Type of biofuel used.
     */
    biofuelType?: string
    /**
     * Share of biofuel in the fuel mix (0 to 1).
     */
    biofuelShare?: string | null
    /**
     * Type of feedstock used to produce the biofuel.
     */
    feedstockType?: string
}
