// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { FuelConsumption } from './FuelConsumption.js'
import type { NullEnum } from './NullEnum.js'
import type { SimpleSeaShippingMethod } from './SimpleSeaShippingMethod.js'

export type ShipmentSeaMethodResponse = {
    vesselImoNumber: string | null
    vesselType: SimpleSeaShippingMethod | 'container_ship' | NullEnum
    refrigerated: boolean | null
    vesselName: string | null
    voyageNumber: string | null
    fuelConsumption: FuelConsumption | NullEnum
    secondaryFuelConsumption: FuelConsumption | NullEnum
    biofuelType: string | null
    biofuelShare: string | null
    feedstockType: string | null
}
