// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { FuelConsumption } from './FuelConsumption.js'
import type { NullEnum } from './NullEnum.js'

export type ShipmentRailMethodResponse = {
    trainType: ShipmentRailMethodResponse.train_type
    fuelConsumption: FuelConsumption | NullEnum
    biofuelType: string | null
    biofuelShare: string | null
    feedstockType: string | null
}

export namespace ShipmentRailMethodResponse {
    export enum train_type {
        DIESEL_FREIGHT_TRAIN = 'diesel_freight_train',
        ELECTRIC_FREIGHT_TRAIN = 'electric_freight_train',
    }
}
