// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { BaseShippingLegEmissionEstimate } from './BaseShippingLegEmissionEstimate.js'
import type { ConvertedShipment } from './ConvertedShipment.js'
import type { NullEnum } from './NullEnum.js'
import type { ResolvedShippingLegEmissionEstimate } from './ResolvedShippingLegEmissionEstimate.js'
import type { ShipmentConversionMethod } from './ShipmentConversionMethod.js'

export type ShippingLegEmissionEstimate = BaseShippingLegEmissionEstimate & {
    /**
     * The shipment after conversion to the emission factor unit (mass to/from TEU).
     *
     * `null` if no conversion was necessary.
     *
     */
    convertedShipment: ConvertedShipment | NullEnum
    /**
     * The method we used to convert the shipment to the emission factor unit.
     *
     * `null` if no conversion was necessary.
     *
     */
    shipmentConversionMethod: ShipmentConversionMethod | NullEnum
    /**
     * If the input shipping method resulted in multiple legs being detected these
     * will be separately calculated and shown here.
     *
     */
    resolvedLegs?: Array<ResolvedShippingLegEmissionEstimate>
}
