// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { FuelConsumption } from './FuelConsumption.js'

/**
 * Rail transport method with shipment-specific reporting fields.
 *
 */
export type ShipmentRailMethod = {
    /**
     * Type of train.
     */
    trainType: ShipmentRailMethod.train_type
    /**
     * Fuel or energy consumption for this leg.
     */
    fuelConsumption?: FuelConsumption
    /**
     * Type of biofuel used.
     */
    biofuelType?: string
    /**
     * Share of biofuel in the fuel mix (0 to 1).
     */
    biofuelShare?: string | null
    /**
     * Type of feedstock used to produce the biofuel.
     */
    feedstockType?: string
}

export namespace ShipmentRailMethod {
    /**
     * Type of train.
     */
    export enum train_type {
        DIESEL_FREIGHT_TRAIN = 'diesel_freight_train',
        ELECTRIC_FREIGHT_TRAIN = 'electric_freight_train',
    }
}
