// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type ShipmentBatchRowSuccess = {
    /**
     * Zero-based index of the input row.
     */
    rowIndex: number
    status: ShipmentBatchRowSuccess.status
    /**
     * Encoded shipment identifier.
     */
    shipmentId: string
}

export namespace ShipmentBatchRowSuccess {
    export enum status {
        SUCCESS = 'success',
    }
}
