// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { AirShippingMethod } from './AirShippingMethod.js'
import type { LogisticsSiteMethod } from './LogisticsSiteMethod.js'
import type { ShipmentRailMethod } from './ShipmentRailMethod.js'
import type { ShipmentRoadMethod } from './ShipmentRoadMethod.js'
import type { ShipmentSeaMethod } from './ShipmentSeaMethod.js'
import type { SimpleShipmentMethod } from './SimpleShipmentMethod.js'

/**
 * Transport method for a shipment leg. Extends the existing shipping method
 * variants with shipment-specific reporting fields.
 *
 */
export type ShipmentMethod =
    | SimpleShipmentMethod
    | ShipmentRoadMethod
    | AirShippingMethod
    | ShipmentSeaMethod
    | ShipmentRailMethod
    | LogisticsSiteMethod
