// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { Distance } from './Distance.js'
import type { ShippingSourceDestination } from './ShippingSourceDestination.js'

/**
 * Provide the route of the leg using either the total `distance` travelled, or the `source` and `destination` location.
 *
 * If shipping between unusual or remote locations, provide `distance` directly for best results
 *
 */
export type ShippingRoute = Distance | ShippingSourceDestination
