// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { Address } from './Address.js'
import type { AirportCode } from './AirportCode.js'
import type { GeographicCoordinates } from './GeographicCoordinates.js'
import type { Locode } from './Locode.js'
import type { TransitCorridor } from './TransitCorridor.js'

export type ShippingSourceDestination = {
    source: Address | GeographicCoordinates | Locode | AirportCode
    destination: Address | GeographicCoordinates | Locode | AirportCode
    transitCorridor?: TransitCorridor
}
