// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type ShipmentBatchRowFailure = {
    /**
     * Zero-based index of the input row.
     */
    rowIndex: number
    status: ShipmentBatchRowFailure.status
    /**
     * Row-level processing error.
     */
    error: string
}

export namespace ShipmentBatchRowFailure {
    export enum status {
        FAILED = 'failed',
    }
}
