// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { FuelConsumption } from './FuelConsumption.js'
import type { Mass } from './Mass.js'
import type { NullEnum } from './NullEnum.js'
import type { RoadEmissionStandard } from './RoadEmissionStandard.js'
import type { RoadFuel } from './RoadFuel.js'
import type { RoadGradient } from './RoadGradient.js'
import type { RoadSituation } from './RoadSituation.js'
import type { RoadVehicleType } from './RoadVehicleType.js'

export type ShipmentRoadMethodResponse = {
    vehicleType: RoadVehicleType | 'truck'
    fuel: RoadFuel | NullEnum
    gradient: RoadGradient | NullEnum
    situation: RoadSituation | NullEnum
    emissionStandard: RoadEmissionStandard | NullEnum
    refrigerated: boolean | null
    truckLicensePlate: string | null
    trailerLicensePlate: string | null
    vin: string | null
    roadType: string | null
    grossVehicleMassRating: Mass | NullEnum
    fuelConsumption: FuelConsumption | NullEnum
    secondaryFuelConsumption: FuelConsumption | NullEnum
    biofuelType: string | null
    biofuelShare: string | null
    feedstockType: string | null
}
