// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * High-level mode of transport for the shipment.
 */
export enum ShipmentModeOfTransport {
    ROAD = 'road',
    SEA = 'sea',
    AIR = 'air',
    RAIL = 'rail',
    INLAND_WATERWAY = 'inland_waterway',
    MULTIMODAL = 'multimodal',
}
