// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * Describes through which channel the batch was created.
 *
 * * `api` — submitted directly through the shipments API
 * * `data_sheet` — submitted as a data sheet through the Lune uploader
 *
 */
export enum ShipmentBatchSource {
    API = 'api',
    DATA_SHEET = 'data_sheet',
}
