// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { ContainerShippingMethod } from './ContainerShippingMethod.js'
import type { FuelConsumption } from './FuelConsumption.js'
import type { IdentifiedVesselShippingMethod } from './IdentifiedVesselShippingMethod.js'
import type { InferredVesselShippingMethod } from './InferredVesselShippingMethod.js'

/**
 * Sea transport method with shipment-specific reporting fields such as
 * voyage number and fuel consumption.
 *
 */
export type ShipmentSeaMethod = (
    | ContainerShippingMethod
    | IdentifiedVesselShippingMethod
    | InferredVesselShippingMethod
) & {
    /**
     * Name of the vessel (if not already provided via IdentifiedVesselShippingMethod).
     */
    vesselName?: string
    /**
     * Voyage number.
     */
    voyageNumber?: string
    /**
     * Primary fuel consumption for this leg.
     */
    fuelConsumption?: FuelConsumption
    /**
     * Secondary fuel consumption.
     */
    secondaryFuelConsumption?: FuelConsumption
    /**
     * Type of biofuel used.
     */
    biofuelType?: string
    /**
     * Share of biofuel in the fuel mix (0 to 1).
     */
    biofuelShare?: string
    /**
     * Type of feedstock used to produce the biofuel.
     */
    feedstockType?: string
}
