// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { ContainerShippingMethod } from './ContainerShippingMethod.js'
import type { IdentifiedVesselShippingMethod } from './IdentifiedVesselShippingMethod.js'
import type { SeaShippingMethod } from './SeaShippingMethod.js'
import type { SimpleShippingMethod } from './SimpleShippingMethod.js'

export type ShippingMethod =
    | SimpleShippingMethod
    | SeaShippingMethod
    | ContainerShippingMethod
    | IdentifiedVesselShippingMethod
