// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { Mass } from './Mass.js'

/**
 * Either a mass given in kilograms or tonnes (`mass`) or the number of [Twenty-foot Equivalent
 * Units (TEUs)](https://en.wikipedia.org/wiki/Twenty-foot_equivalent_unit) (with their cargo type,
 * optionally). Note that providing `mass` will result in more accurate estimates for methods other
 * than `container_ship`. Estimates using `container_ship` are more precise when the shipment is given
 * in TEUs.
 *
 */
export type Shipment =
    | {
          mass: Mass
      }
    | {
          containers: string
          /**
           * If omitted, `average` is assumed.
           *
           * The following conversions apply:
           * * `lightweight`: 1 container = 6 tonnes
           * * `average`: 1 container = 10 tonnes
           * * `heavyweight`: 1 container = 14.5 tonnes
           * * `container_only`: 1 container = 2 tonnes
           *
           */
          cargoType?: Shipment.cargo_type
          mass?: Mass
      }

export namespace Shipment {
    /**
     * If omitted, `average` is assumed.
     *
     * The following conversions apply:
     * * `lightweight`: 1 container = 6 tonnes
     * * `average`: 1 container = 10 tonnes
     * * `heavyweight`: 1 container = 14.5 tonnes
     * * `container_only`: 1 container = 2 tonnes
     *
     */
    export enum cargo_type {
        LIGHTWEIGHT = 'lightweight',
        AVERAGE = 'average',
        HEAVYWEIGHT = 'heavyweight',
        CONTAINER_ONLY = 'container_only',
    }
}
