// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * A subset of simple transport methods available for shipment legs.
 * Covers rail and air transport. Road and sea transport should use their
 * dedicated shipment method schemas instead.
 *
 * Note: Inland waterway transport is not currently supported when
 * creating shipments via this API.
 *
 * # Rail transport
 * For rail transport, values follow the pattern:
 * `{train_type}_{region}_{load_characteristics}`
 *
 * # Air transport
 * * `cargo_plane`: A full freighter plane.
 * * `passenger_plane`: Belly freight only.
 * * `plane`: Unknown freight capacity (weighted average).
 *
 */
export enum SimpleShipmentMethod {
    DIESEL_FREIGHT_TRAIN = 'diesel_freight_train',
    ELECTRIC_FREIGHT_TRAIN = 'electric_freight_train',
    RAIL = 'rail',
    PLANE = 'plane',
    PASSENGER_PLANE = 'passenger_plane',
    CARGO_PLANE = 'cargo_plane',
}
