// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { DataQualityScore } from './DataQualityScore.js'
import type { EstimateQuote } from './EstimateQuote.js'
import type { IsShipment } from './IsShipment.js'
import type { Metadata } from './Metadata.js'
import type { NullEnum } from './NullEnum.js'
import type { ShippedAt } from './ShippedAt.js'
import type { ShippingEstimateRequest } from './ShippingEstimateRequest.js'
import type { ShippingLegEmissionEstimate } from './ShippingLegEmissionEstimate.js'
import type { Url } from './Url.js'

export type SingleShippingEmissionEstimate = ShippingLegEmissionEstimate & {
    /**
     * The emission calculation unique identifier
     */
    id: string
    isShipment: IsShipment
    shippedAt: ShippedAt
    quote: EstimateQuote
    request: ShippingEstimateRequest
    metadata?: Metadata
    /**
     * An external accessible URL linking to a detailed page that provides complete information about the estimate.
     */
    externalEstimateUrl: Url | NullEnum
    /**
     * Represents the quality of the emission estimation.
     *
     */
    dataQualityScore: DataQualityScore | NullEnum
    /**
     * Identifies the source used to create the estimate.
     */
    source?: SingleShippingEmissionEstimate.source
    /**
     * The date and time when the estimate was created.
     */
    createdAt: string
    /**
     * Name of the uploaded data sheet.
     */
    filename: string | NullEnum
    /**
     * Full name of the user that uploaded the data sheet.
     */
    userFullname: string | NullEnum
}

export namespace SingleShippingEmissionEstimate {
    /**
     * Identifies the source used to create the estimate.
     */
    export enum source {
        API = 'api',
        DASHBOARD = 'dashboard',
        CSV = 'csv',
        CHAIN_IO = 'chain_io',
        ECOTRANSIT_CSV = 'ecotransit_csv',
        WIDGET = 'widget',
        ECOTRANSIT = 'ecotransit',
        BLUE_YONDER = 'blue_yonder',
        RFQ = 'rfq',
    }
}
