// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { EstimateQuote } from './EstimateQuote.js'
import type { ShippingEstimateRequest } from './ShippingEstimateRequest.js'
import type { ShippingLegEmissionEstimate } from './ShippingLegEmissionEstimate.js'

export type SingleShippingEmissionEstimate = ShippingLegEmissionEstimate & {
    /**
     * The emission calculation unique identifier
     */
    id: string
    quote: EstimateQuote
    request: ShippingEstimateRequest
}
