// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { EstimateQuote } from './EstimateQuote.js'
import type { ShippingEstimateRequest } from './ShippingEstimateRequest.js'
import type { ShippingLegEmissionEstimate } from './ShippingLegEmissionEstimate.js'

export type SingleShippingEmissionEstimate = ShippingLegEmissionEstimate & {
    /**
     * The emission calculation unique identifier
     */
    id: string
    /**
     * When true, the estimate refers to a shipment.
     * This property exists in order for clients to distinguish between estimates made for informative purposes or during booking flows from estimates made for shipments where goods are moved.
     * You can mark an estimate as shipment at any time.
     *
     */
    isShipment: boolean
    quote: EstimateQuote
    request: ShippingEstimateRequest
}
