// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { EstimateMass } from './EstimateMass.js'
import type { SmartScanEstimateTransactionLineItem } from './SmartScanEstimateTransactionLineItem.js'

/**
 * Smart scan line item estimate.
 */
export type SmartScanEmissionEstimateLineItem = {
    mass: EstimateMass
    /**
     * Identifies the type of the line item emission estimate. New values are expected to be
     * introduced over time and considered to be a non breaking change.
     *
     */
    type: SmartScanEmissionEstimateLineItem.type
} & SmartScanEstimateTransactionLineItem

export namespace SmartScanEmissionEstimateLineItem {
    /**
     * Identifies the type of the line item emission estimate. New values are expected to be
     * introduced over time and considered to be a non breaking change.
     *
     */
    export enum type {
        TRANSACTION = 'transaction',
    }
}
