// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { BundleSelectionRequest } from './BundleSelectionRequest.js'
import type { LogisticsSiteMethod } from './LogisticsSiteMethod.js'
import type { MassUnit } from './MassUnit.js'
import type { Shipment } from './Shipment.js'
import type { ShippingCountryCode } from './ShippingCountryCode.js'
import type { ShippingMethod } from './ShippingMethod.js'
import type { ShippingRoute } from './ShippingRoute.js'

/**
 * Parameters for estimating multi-leg shipping emissions
 */
export type StoredMultiLegShippingEstimateRequest = {
    shipment: Shipment
    /**
     * An array representing all the legs of a shipment.
     */
    legs: Array<
        | {
              route: ShippingRoute
              method: ShippingMethod
              countryCode?: ShippingCountryCode
          }
        | {
              method: LogisticsSiteMethod
          }
    >
    /**
     * A name to reference this calculation.
     */
    name?: string
    bundleSelection?: BundleSelectionRequest
    /**
     * Selects to which precision to truncate the quantities assigned to each bundle.
     */
    quantityTrunc?: MassUnit
}
