// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * The list of supported UN Sustainable Development Goals (SDGs).
 *
 * The array is sorted by the goal number (the `un_sdg_number` property), ascending.
 *
 */
export type SupportedUNSdg = Array<{
    /**
     * The number which identifies the specific UN SDG.
     */
    unSdgNumber: number
    /**
     * The total number of projects supporting this UN SDG.
     */
    occurrences: number
}> | null
