// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * The sustainability page status which determines whether it is visible to the public.
 */
export enum SustainabilityPageStatus {
    ENABLED = 'enabled',
    DISABLED = 'disabled',
}
