// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * The sustainability page title stat format.
 */
export enum SustainabilityPageTitle {
    BY_VOLUME = 'by_volume',
    BY_PRICE = 'by_price',
}
