// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { NullEnum } from './NullEnum.js'
import type { SustainabilityPageCustomDescription } from './SustainabilityPageCustomDescription.js'
import type { SustainabilityPageDescription } from './SustainabilityPageDescription.js'
import type { SustainabilityPageSections } from './SustainabilityPageSections.js'
import type { SustainabilityPageSlug } from './SustainabilityPageSlug.js'
import type { SustainabilityPageStatus } from './SustainabilityPageStatus.js'
import type { SustainabilityPageTitle } from './SustainabilityPageTitle.js'

export type SustainabilityPageRequest = {
    status: SustainabilityPageStatus
    slug: SustainabilityPageSlug
    title: SustainabilityPageTitle
    description?: SustainabilityPageDescription | NullEnum
    customDescription?: SustainabilityPageCustomDescription
    sections: SustainabilityPageSections
}
