// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { SustainabilityPageSection } from './SustainabilityPageSection.js'

/**
 * The sustainability page sections that will be displayed in the page. Only a single instance of each section type is allowed and the order is irrelevant.
 */
export type SustainabilityPageSectionsNullable = Array<SustainabilityPageSection> | null
