// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { TransactionDocumentEmissionEstimateLineItem } from './TransactionDocumentEmissionEstimateLineItem.js'

/**
 * Line items for the transaction document estimate. At least one line item will always exist.
 */
export type TransactionDocumentEmissionEstimateLineItems =
    Array<TransactionDocumentEmissionEstimateLineItem>
