// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { TransactionDocumentEstimateRequest } from './TransactionDocumentEstimateRequest.js'

export type TransactionDocumentEstimateRequestAsync = TransactionDocumentEstimateRequest & {
    /**
     * ID to reconcile requests and responses on the client side. This value is returned to clients in webhook events.
     *
     */
    correlationId?: string
}
