// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { EmissionEstimateResponse } from './EmissionEstimateResponse.js'
import type { IsTransaction } from './IsTransaction.js'
import type { NullEnum } from './NullEnum.js'
import type { TransactionEmissionEstimateBaseFields } from './TransactionEmissionEstimateBaseFields.js'
import type { TransactionEstimateRequest } from './TransactionEstimateRequest.js'
import type { TransactionProcessedAt } from './TransactionProcessedAt.js'
import type { Url } from './Url.js'

export type TransactionEmissionEstimate = EmissionEstimateResponse &
    TransactionEmissionEstimateBaseFields & {
        request: TransactionEstimateRequest
        /**
         * An external accessible URL linking to a detailed page that provides complete information about the estimate.
         */
        externalEstimateUrl: Url | NullEnum
        isTransaction: IsTransaction | NullEnum
        transactionProcessedAt: TransactionProcessedAt | NullEnum
    }
