// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { BundleSelectionRequest } from './BundleSelectionRequest.js'
import type { Diet } from './Diet.js'
import type { EstimateIdempotencyKey } from './EstimateIdempotencyKey.js'
import type { Merchant } from './Merchant.js'
import type { Metadata } from './Metadata.js'
import type { MonetaryAmount } from './MonetaryAmount.js'
import type { QuantityTrunc } from './QuantityTrunc.js'

/**
 * Parameters for estimating emissions associated with purchasing goods or services.
 */
export type TransactionEstimateRequest = {
    /**
     * A name to reference this calculation.
     */
    name?: string
    /**
     * Monetary value of the transaction. This should exclude shipping and taxes.
     */
    value: MonetaryAmount
    /**
     * Merchant from whom the goods or services the purchase was made
     */
    merchant: Merchant
    /**
     * Individual diet. Used to better estimate  food-related purchases.
     */
    diet?: Diet
    bundleSelection?: BundleSelectionRequest
    quantityTrunc?: QuantityTrunc
    metadata?: Metadata
    idempotencyKey?: EstimateIdempotencyKey
}
