// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { MerchantCategoryCode } from './MerchantCategoryCode.js'
import type { MonetaryAmount } from './MonetaryAmount.js'
import type { NullEnum } from './NullEnum.js'
import type { TransactionEmissionEstimateBaseFields } from './TransactionEmissionEstimateBaseFields.js'

/**
 * A transaction document line item describing the properties that have been idenfitied.
 */
export type TransactionDocumentEstimateTransactionLineItem = TransactionEmissionEstimateBaseFields &
    ({
        /**
         * The 3-character country code that has been identified.
         */
        countryCode: string
        value: MonetaryAmount
    } & (
        | {
              /**
               * The line items that has been identified.
               */
              item: string
              category: string | NullEnum
              categoryCode: NullEnum
          }
        | {
              item: NullEnum
              category: NullEnum
              categoryCode: MerchantCategoryCode
          }
    ))
