// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { CurrencyCode } from './CurrencyCode.js'
import type { Diet } from './Diet.js'
import type { MonetaryAmountValue } from './MonetaryAmountValue.js'
import type { OptionalMerchant } from './OptionalMerchant.js'

/**
 * Parameters for estimating emissions associated with purchasing goods or services.
 */
export type TransactionEstimateRequestData = {
    value?: MonetaryAmountValue
    currency?: CurrencyCode
    /**
     * Merchant from whom the goods or services the purchase was made
     */
    merchant?: OptionalMerchant
    /**
     * Individual diet. Used to better estimate  food-related purchases.
     */
    diet?: Diet
}
