// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { BundleSelectionRequest } from './BundleSelectionRequest.js'
import type { Diet } from './Diet.js'
import type { Merchant } from './Merchant.js'
import type { Metadata } from './Metadata.js'
import type { MonetaryAmount } from './MonetaryAmount.js'
import type { QuantityTrunc } from './QuantityTrunc.js'
import type { RegionFallback } from './RegionFallback.js'

export type TransactionEstimatePartialRequest = {
    /**
     * A name to reference this calculation.
     */
    name?: string
    /**
     * Specify the monetary value of the transaction, excluding shipping and taxes.
     */
    value: MonetaryAmount
    /**
     * The merchant from whom the goods or services were purchased.
     */
    merchant: Merchant
    /**
     * Specify individual dietary preferences to improve estimates for food-related purchases.
     */
    diet?: Diet
    bundleSelection?: BundleSelectionRequest
    quantityTrunc?: QuantityTrunc
    metadata?: Metadata
    regionFallback?: RegionFallback
}
