// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * This property captures the exact date and time at which the transaction was recorded and processed.
 *
 * If a value is provided when creating or updating an estimate we use the value.
 * Otherwise defaults to the current time when creating estimates and remains
 * unchanged when updating estimates.
 *
 * This property must be formatted as RFC 3339, section 5.6 timestamp.
 *
 * Examples:
 * * 2023-12-01T12:30:30.000Z
 * * 2023-12-01T12:30:30Z
 * * 2023-12-01T11:30:30+01.00
 *
 */
export type TransactionProcessedAt = string
