// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * The transit corridor used for sea shipments. This is used to improve the accuracy of the estimate.
 * If not provided, the shortest route is calculated.
 *
 * Only applicable to sea shipments.
 *
 */
export enum TransitCorridor {
    PANAMA = 'panama',
    SUEZ = 'suez',
    CAPE_OF_GOOD_HOPE = 'cape_of_good_hope',
    NORTHWEST_PASSAGE = 'northwest_passage',
    NORTHEAST_PASSAGE = 'northeast_passage',
    CAPE_HORN = 'cape_horn',
}
