// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { EmissionEstimateResponse } from './EmissionEstimateResponse.js'
import type { TransactionEstimateRequest } from './TransactionEstimateRequest.js'

export type TransactionEmissionEstimate = EmissionEstimateResponse & {
    request: TransactionEstimateRequest
    /**
     * The most accurate term matching the search.
     *
     * The emission factor for this term is used to compute the emission estimate.
     *
     */
    searchTermMatch?: string
}
