// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { EmissionFactorActivity } from './EmissionFactorActivity.js'
import type { EmissionFactorWithGasEmissions } from './EmissionFactorWithGasEmissions.js'
import type { NullEnum } from './NullEnum.js'
import type { TransactionEmissionSearchFields } from './TransactionEmissionSearchFields.js'

/**
 * A transaction document line item describing the activity related properties that have been identified.
 */
export type TransactionDocumentEstimateActivityLineItem = TransactionEmissionSearchFields & {
    /**
     * The line items that has been identified.
     */
    item: string
    activity: EmissionFactorActivity
    /**
     * This property is `null` for any estimate created before 01/12/2024
     */
    emissionFactor: EmissionFactorWithGasEmissions | NullEnum
}
