// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type UpdateShippingEstimateIsShipmentRequest = {
    /**
     * Is the emission calculation referring to a shipment that was made in real life.
     */
    isShipment: boolean
}
