// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { EstimateIdempotencyKey } from './EstimateIdempotencyKey.js'
import type { IsShipment } from './IsShipment.js'
import type { Metadata } from './Metadata.js'
import type { ShippedAt } from './ShippedAt.js'

export type UpdateShippingEstimateAnnotationsRequest =
    | {
          isShipment: IsShipment
          shippedAt?: ShippedAt
          metadata?: Metadata
          idempotencyKey?: EstimateIdempotencyKey
      }
    | {
          shippedAt: ShippedAt
          metadata?: Metadata
          idempotencyKey?: EstimateIdempotencyKey
      }
    | {
          metadata: Metadata
          idempotencyKey?: EstimateIdempotencyKey
      }
    | {
          idempotencyKey: EstimateIdempotencyKey
      }
