// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type VariableFuelSeaShippingMethod = {
    /**
     * Vessel sizes:
     * * `sea_oil_tanker_*`:
     * * `small` – <5 dwkt
     * * `medium` – 20-60 dwkt
     * * `large` – 112-200 dwkt
     * * `sea_general_cargo_*`:
     * * `small` – 5-10 dwkt
     * * `large` – 10-20 dwkt
     * * `sea_bulk_carrier_small` - <10 dwkt
     * * `sea_ropax` – 2-5 dwkt
     *
     */
    vesselType: VariableFuelSeaShippingMethod.vessel_type
    fuel?: VariableFuelSeaShippingMethod.fuel
}

export namespace VariableFuelSeaShippingMethod {
    /**
     * Vessel sizes:
     * * `sea_oil_tanker_*`:
     * * `small` – <5 dwkt
     * * `medium` – 20-60 dwkt
     * * `large` – 112-200 dwkt
     * * `sea_general_cargo_*`:
     * * `small` – 5-10 dwkt
     * * `large` – 10-20 dwkt
     * * `sea_bulk_carrier_small` - <10 dwkt
     * * `sea_ropax` – 2-5 dwkt
     *
     */
    export enum vessel_type {
        SEA_OIL_TANKER_SMALL = 'sea_oil_tanker_small',
        SEA_OIL_TANKER_MEDIUM = 'sea_oil_tanker_medium',
        SEA_OIL_TANKER_LARGE = 'sea_oil_tanker_large',
        SEA_GENERAL_CARGO_SMALL = 'sea_general_cargo_small',
        SEA_GENERAL_CARGO_LARGE = 'sea_general_cargo_large',
        SEA_BULK_CARRIER_SMALL = 'sea_bulk_carrier_small',
        SEA_ROPAX = 'sea_ropax',
    }

    export enum fuel {
        HFO = 'HFO',
        MGO = 'MGO',
    }
}
