// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type VesselInferenceMethodDetails = {
    /**
     * * `carrier_schedules` – Vessel ID inferred using carrier schedules
     * * `ais_port_calls` – Vessel ID inferred using historic AIS data
     *
     */
    method: VesselInferenceMethodDetails.method
    /**
     * Describes details of vessel inference method
     *
     */
    details: string
}

export namespace VesselInferenceMethodDetails {
    /**
     * * `carrier_schedules` – Vessel ID inferred using carrier schedules
     * * `ais_port_calls` – Vessel ID inferred using historic AIS data
     *
     */
    export enum method {
        CARRIER_SCHEDULES = 'carrier_schedules',
        AIS_PORT_CALLS = 'ais_port_calls',
    }
}
