// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { VolumeUnit } from './VolumeUnit.js'

/**
 * A volume measurement.
 */
export type Volume = {
    amount: string
    unit: VolumeUnit
}
