// =========================================================================================
//
// This file is AUTO-GENERATED by https://github.com/lune-climate/openapi-typescript-codegen
//
// In most cases you DON'T WANT TO MAKE MANUAL CHANGES to it – they WILL BE OVERWRITTEN.
//
// =========================================================================================

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * Timeseries containing the total emissions (tCO₂e) for the the three WTW stages (wtt, ttw and unknown). Each element refers to a particular timeframe as seen on `date`.
 */
export type WtwBreakdownTimeseries = Array<{
    date: string
    wtt: number
    ttw: number
    unknown: number
}>
