name: Create PR with bump patch version

# Perform workflow based on human approval
on:
  - workflow_dispatch

permissions: {}

jobs:
  build:
    name: Bump version (patch) and create PR.
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout the code
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
        with:
          persist-credentials: false
      - name: Bump version (patch)
        run: docker compose -f docker-compose-ci.yml run bump_version_patch
      - name: Create PR with changes
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.CLIENT_REBUILD_TOKEN_GITHUB }}
          commit-message: Bump version (patch)
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          base: master
          branch: auto-version-update-patch
          delete-branch: true
          title: 'Bump version (patch)'
          body: |
            Action to bump version (patch) was triggered. Check changes and approve accordingly.
          labels: |
            Bump version (patch)
            Automated PR
          reviewers: lune-eng
          draft: false
