name: Create PR with bump major version

# Perform workflow based on human approval
on:
  - workflow_dispatch

permissions: {}

jobs:
  build:
    name: Bump version (major) and create PR.
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout the code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Bump version (major)
        run: docker compose -f docker-compose-ci.yml run bump_version_major
      - name: Create PR with changes
        uses: peter-evans/create-pull-request@18f7dc018cc2cd597073088f7c7591b9d1c02672 # v3.14.0
        with:
          token: ${{ secrets.CLIENT_REBUILD_TOKEN_GITHUB }}
          commit-message: Bump version (major)
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          base: master
          branch: auto-version-update-major
          delete-branch: true
          title: 'Bump version (major)'
          body: |
            Action to bump version (major) was triggered. Check changes and approve accordingly.
          labels: |
            Bump version (major)
            Automated PR
          reviewers: lune-eng
          draft: false
