name: Create PR with bump major version

# Perform workflow based on human approval
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Bump version (major) and create PR.
    runs-on: ubuntu-latest
    # The environment is used to guarantee that a manual approval is required.
    environment: bump_version

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Bump version (major)
        run: docker-compose -f docker-compose-ci.yml run bump_version_major
      - name: Create PR with changes
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.CLIENT_REBUILD_TOKEN_GITHUB }}
          commit-message: Bump version (major)
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          base: master
          branch: auto-version-update-major
          delete-branch: true
          title: 'Bump version (major)'
          body: |
            Action to bump version (major) was triggered. Check changes and approve accordingly.
          labels: |
            Bump version (major)
            Automated PR
          reviewers: lune-eng
          draft: false
