name: Build client on CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build schema from source
        run: id && ls -lah && docker-compose -f docker-compose-ci.yml run build_from_source
