name: Build client on CI

on: [push]

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout the code
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
      - name: Build schema from source
        run: docker compose -f docker-compose-ci.yml run update_from_remote_schema
